from typing import Any, Callable, Sequence

from netius import DatagramClient, Request, Response

PEER_ID_SIZE: int
CONTACT_SIZE: int
NODE_SIZE: int
BUCKET_SIZE: int
BOOTSTRAP_NODES: tuple[tuple[str, int], ...]

class DHTRequest(Request):
    peer_id: bytes | str | None
    host: str
    port: int
    type: str
    args: tuple[tuple[Any, ...]]
    kwargs: dict[str, Any]

    def __init__(
        self,
        peer_id: bytes | str | None,
        host: str = ...,
        port: int = ...,
        type: str = ...,
        callback: Callable[[DHTResponse], Any] | None = ...,
        *args,
        **kwargs
    ): ...
    @classmethod
    def contact(cls, host: str, port: int) -> bytes: ...
    def request(self) -> bytes: ...
    def ping(self) -> dict[str, Any]: ...
    def find_node(self) -> dict[str, Any]: ...
    def get_peers(self) -> dict[str, Any]: ...
    def announce_peer(self) -> dict[str, Any]: ...
    def _get_peer_id(self) -> bytes | None: ...

class DHTResponse(Response):
    info: dict[str, Any]

    def __init__(self, data: bytes): ...
    def parse(self): ...
    def get_id(self) -> int: ...  # type: ignore[override]
    def get_payload(self) -> dict[str, Any]: ...
    def get_nodes(self) -> list[DHTNode]: ...
    def is_error(self) -> bool: ...
    def is_response(self) -> bool: ...

class DHTNode:
    peer_id: bytes
    host: str
    port: int

    def __init__(self, peer_id: bytes | str, host: str = ..., port: int = ...): ...
    @classmethod
    def unpack(cls, data: bytes | str) -> list[DHTNode]: ...
    def distance(self, peer_id: bytes | str) -> int: ...
    def is_valid(self) -> bool: ...
    def _peer_id_int(self) -> int: ...

class DHTRoutingTable:
    peer_id: bytes
    bucket_size: int
    buckets: dict[int, list[DHTNode]]

    def __init__(self, peer_id: bytes | str, bucket_size: int = ...): ...
    def add(self, node: DHTNode) -> bool: ...
    def closest(self, target: bytes | str, count: int = ...) -> list[DHTNode]: ...
    def _bucket_index(self, node: DHTNode) -> int: ...
    def _has_node(self, bucket: Sequence[DHTNode], node: DHTNode) -> bool: ...

class DHTClient(DatagramClient):
    def ping(self, host: str, port: int, peer_id: bytes | str, *args, **kwargs): ...
    def find_node(self, *args, **kwargs): ...
    def get_peers(self, *args, **kwargs): ...
    def routing(self, peer_id: bytes | str) -> DHTRoutingTable: ...
    def bootstrap(
        self,
        peer_id: bytes | str,
        target: bytes | str | None = ...,
        nodes: Sequence[DHTNode | tuple[str, int]] | None = ...,
        callback: Callable[[DHTResponse], Any] | None = ...,
        **kwargs
    ) -> list[Any]: ...
    def lookup(
        self,
        peer_id: bytes | str,
        target: bytes | str,
        type: str = ...,
        nodes: Sequence[DHTNode | tuple[str, int]] | None = ...,
        callback: Callable[[DHTResponse], Any] | None = ...,
        **kwargs
    ) -> list[Any]: ...
    def _bootstrap_nodes(self) -> list[tuple[str, int]]: ...
    def query(
        self,
        host: str = ...,
        port: int = ...,
        peer_id: bytes | str | None = ...,
        type: str = ...,
        callback: Callable[[DHTResponse], Any] | None = ...,
        *args,
        **kwargs
    ): ...
    def on_data(self, address: Any, data: bytes): ...
    def on_data_dht(self, address: Any, response: DHTResponse): ...
