from typing import Any, Callable, Mapping

from netius import ClientAgent, DatagramProtocol, Request, Response

DNS_QUERY: int
DNS_RESPONSE: int
DNS_SQUERY: int
DNS_IQUERY: int
DNS_STATUS: int
DNS_AA: int
DNS_TC: int
DNS_RD: int
DNS_TYPES: Mapping[str, int]
DNS_CLASSES: Mapping[str, int]
DNS_TYPES_R: Mapping[int, str]
DNS_CLASSES_R: Mapping[int, str]

class DNSRequest(Request):
    name: str
    type: str
    cls: str

    def __init__(
        self,
        name: str,
        type: str = ...,
        cls: str = ...,
        callback: Callable[..., Any] | None = ...,
    ): ...
    def request(self) -> bytes: ...
    def _query(self, name: str, type: str = ..., cls: str = ...) -> bytes: ...
    def _label(self, value: str) -> bytes: ...

class DNSResponse(Response):
    def parse(self): ...
    def get_id(self) -> int: ...  # type: ignore[override]
    def parse_qd(
        self, data: bytes, index: int
    ) -> tuple[int, tuple[bytes, str, str]]: ...
    def parse_an(
        self, data: bytes, index: int
    ) -> tuple[int, tuple[bytes, str, str, int, Any]]: ...
    def parse_payload(
        self, data: bytes, index: int, type_s: str
    ) -> tuple[int, Any]: ...
    def parse_a(self, data: bytes, index: int) -> tuple[int, str]: ...
    def parse_aaaa(self, data: bytes, index: int) -> tuple[int, str]: ...
    def parse_mx(self, data: bytes, index: int) -> tuple[int, tuple[int, bytes]]: ...
    def parse_cname(self, data: bytes, index: int) -> tuple[int, bytes]: ...
    def parse_ns(self, data: bytes, index: int): ...
    def parse_ar(self, data: bytes, index: int): ...
    def parse_label(self, data: bytes, index: int) -> tuple[int, bytes]: ...
    def parse_pointer(self, data: bytes, index: int) -> tuple[int, bytes]: ...
    def parse_ip4(self, data: bytes, index: int) -> tuple[int, str]: ...
    def parse_ip6(self, data: bytes, index: int) -> tuple[int, str]: ...
    def parse_byte(self, data: bytes, index: int) -> tuple[int, int]: ...
    def parse_short(self, data: bytes, index: int) -> tuple[int, int]: ...
    def parse_long(self, data: bytes, index: int) -> tuple[int, int]: ...
    def parse_long_long(self, data: bytes, index: int) -> tuple[int, int]: ...

class DNSProtocol(DatagramProtocol):
    ns_file_l: list[str] | None

    @classmethod
    def ns_system(cls, type: str = ...) -> str | None: ...
    @classmethod
    def ns_conf(cls, type: str = ..., force: bool = ...) -> list[str]: ...
    @classmethod
    def ns_file(cls, type: str = ..., force: bool = ...) -> list[str] | None: ...
    @classmethod
    def ns_google(cls, type: str = ...) -> list[str]: ...
    @classmethod
    def ns_cloudfare(cls, type: str = ...) -> list[str]: ...
    def query(
        self,
        name: str,
        type: str = ...,
        cls: str = ...,
        ns: str | None = ...,
        callback: Callable[..., Any] | None = ...,
    ): ...
    def on_data(self, address: tuple[str, int], data: bytes): ...
    def on_data_dns(self, address: tuple[str, int], response: DNSResponse): ...

class DNSClient(ClientAgent):
    protocol: type[DNSProtocol]

    @classmethod
    def query_s(
        cls,
        name: str,
        type: str = ...,
        cls_: str = ...,
        ns: str | None = ...,
        callback: Callable[..., Any] | None = ...,
        loop: Any = ...,
    ) -> tuple[Any, DNSProtocol]: ...
