from netius.clients import HTTPClient, HTTPProtocol

class MJPGProtocol(HTTPProtocol):
    MAGIC_JPEG: bytes
    EOI_JPEG: bytes
    buffer_l: list[bytes]

    def __init__(self, *args, **kwargs): ...
    def add_buffer(self, data: bytes): ...
    def get_buffer(self, delete: bool = ...) -> bytes: ...
    def on_partial(self, data: bytes): ...
    def on_frame_mjpg(self, data: bytes): ...

class MJPGClient(HTTPClient):
    protocol: type[MJPGProtocol]
