from email.message import Message
from socket import socket as Socket
from typing import Any, Callable, Sequence

from netius import Connection, StreamClient
from netius.common import SMTPParser

HELO_STATE: int
EHLO_STATE: int
CAPA_STATE: int
STLS_STATE: int
UPGRADE_STATE: int
AUTH_STATE: int
USERNAME_STATE: int
PASSWORD_STATE: int
FROM_STATE: int
TO_STATE: int
DATA_STATE: int
CONTENTS_STATE: int
QUIT_STATE: int
FINAL_STATE: int

class SMTPConnection(Connection):
    AUTH_METHODS: tuple[str, ...]
    parser: SMTPParser | None
    host: str
    froms: Sequence[str] | None
    tos: Sequence[str] | None
    contents: str | None
    username: str | None
    password: str | None
    expected: int | None
    to_index: int
    state: int
    next: int | None
    sindex: int
    sequence: Sequence[int]
    capabilities: Sequence[str]
    messages: list[str]
    greeting: str | None
    queue_response: str | None
    tls_version: str | None
    tls_cipher: tuple[str, str, int] | None
    start_time: float | None
    transcript: list[dict[str, Any]]
    transcript_max: int

    def __init__(self, host: str = ..., *args, **kwargs): ...
    def open(self, *args, **kwargs): ...
    def close(self, *args, **kwargs): ...
    def build(self): ...
    def destroy(self): ...
    def set_smtp(
        self,
        froms: Sequence[str],
        tos: Sequence[str],
        contents: str,
        username: str | None = ...,
        password: str | None = ...,
    ): ...
    def set_sequence(self, sequence: Sequence[int], safe: bool = ...): ...
    def set_message_seq(self, ehlo: bool = ...): ...
    def set_message_stls_seq(self, ehlo: bool = ...): ...
    def set_capabilities(self, capabilities: Sequence[str], force: bool = ...): ...
    def next_sequence(self): ...
    def parse(self, data: bytes) -> int: ...
    def send_smtp(
        self,
        code: str,
        message: str = ...,
        delay: bool = ...,
        callback: Callable[[Connection], Any] | None = ...,
    ) -> int: ...
    def on_line(self, code: str, message: str, is_final: bool = ...): ...
    def call(self): ...
    def skip(self): ...
    def helo_t(self): ...
    def ehlo_t(self): ...
    def capa_t(self): ...
    def stls_t(self): ...
    def upgrade_t(self): ...
    def auth_t(self): ...
    def username_t(self): ...
    def password_t(self): ...
    def mail_t(self): ...
    def rcpt_t(self): ...
    def data_t(self): ...
    def contents_t(self): ...
    def quit_t(self): ...
    def close_t(self): ...
    def pass_t(self): ...
    def helo(self, host: str): ...
    def ehlo(self, host: str): ...
    def starttls(self): ...
    def auth(self, username: str, password: str, method: str = ...): ...
    def auth_plain(self, username: str, password: str): ...
    def auth_login(self, username: str, password: str): ...
    def login_username(self, username: str): ...
    def login_password(self, password: str): ...
    def mail(self, value: str): ...
    def rcpt(self, value: str): ...
    def data(self): ...
    def quit(self): ...
    def set_expected(self, expected: int | None): ...
    def assert_c(self, code: str): ...
    def assert_s(self, expected: int): ...
    def best_auth(self) -> str: ...
    def _transcript_add(self, direction: str, message: str): ...

class SMTPClient(StreamClient):
    host: str
    auto_close: bool
    capture_transcript: bool

    def __init__(
        self,
        host: str | None = ...,
        auto_close: bool = ...,
        capture_transcript: bool = ...,
        *args,
        **kwargs
    ): ...
    @classmethod
    def message_s(
        cls,
        froms: Sequence[str],
        tos: Sequence[str],
        contents: str,
        daemon: bool = ...,
        host: str | None = ...,
        mark: bool = ...,
        callback: Callable[[SMTPClient, dict[str, Any]], Any] | None = ...,
    ): ...
    def message(
        self,
        froms: Sequence[str],
        tos: Sequence[str],
        contents: str,
        message_id: str | None = ...,
        host: str | None = ...,
        port: int = ...,
        username: str | None = ...,
        password: str | None = ...,
        ehlo: bool = ...,
        stls: bool = ...,
        mark: bool = ...,
        comply: bool = ...,
        ensure_loop: bool = ...,
        sequential: bool = ...,
        mx_dedup: bool = ...,
        callback: Callable[[SMTPClient, dict[str, Any]], Any] | None = ...,
        callback_error: (
            Callable[[SMTPClient, dict[str, Any], BaseException | None], Any] | None
        ) = ...,
    ) -> SMTPConnection | None: ...
    def on_connect(self, connection: Connection): ...
    def on_upgrade(self, connection: Connection): ...
    def on_data(self, connection: Connection, data: bytes): ...
    def on_connection_d(self, connection: Connection): ...
    def build_connection(  # type: ignore[override]
        self,
        socket: Socket,
        address: tuple[str, int] | str | None,
        ssl: bool = ...,
    ) -> SMTPConnection: ...
    def comply(
        self,
        contents: str,
        froms: Sequence[str] | None = ...,
        tos: Sequence[str] | None = ...,
        message_id: str | None = ...,
    ) -> str: ...
    def mark(self, contents: str) -> str: ...
    def from_(self, message: Message, value: str): ...
    def to(self, message: Message, value: str): ...
    def message_id(self, message: Message, value: str): ...
    def date(self, message: Message): ...
    def user_agent(self, message: Message): ...
