from socket import socket as Socket
from typing import Any, Callable, Mapping

from netius import Connection, StreamClient
from netius.common import TorrentParser
from netius.servers import TorrentTask

HANDSHAKE_STATE: int
NORMAL_STATE: int
CHOKED: int
UNCHOKED: int
ALIVE_TIMEOUT: float
SPEED_LIMIT: int
BLOCK_SIZE: int
EXTENDED_RESERVED: int
METADATA_BLOCK_SIZE: int
EXTENDED_TYPES: Mapping[int, str]
METADATA_REQUEST: int
METADATA_DATA: int
METADATA_REJECT: int

class TorrentConnection(Connection):
    parser: TorrentParser | None
    max_requests: int
    pend_requests: int
    task: TorrentTask | None
    peer_id: bytes | None
    bitfield: bytes | list[bool]
    state: int
    choked: int
    start: float
    messages: int
    downloaded: int
    requests: list[tuple[int, int]]
    extensions: dict[str, Any]
    metadata_size: int
    metadata: list[bytes | None]

    def __init__(self, max_requests: int = ..., *args, **kwargs): ...
    def open(self, *args, **kwargs): ...
    def close(self, *args, **kwargs): ...
    def on_close(self, connection: Connection): ...
    def on_handshake(
        self, protocol: bytes, reserved: int, info_hash: bytes, peer_id: bytes
    ): ...
    def on_message(self, length: int, type: str, data: bytes): ...
    def parse(self, data: bytes): ...
    def handle(self, type: str, data: bytes): ...
    def bitfield_t(self, data: bytes): ...
    def choke_t(self, data: bytes): ...
    def unchoke_t(self, data: bytes): ...
    def piece_t(self, data: bytes): ...
    def port_t(self, data: bytes): ...
    def extended_t(self, data: bytes): ...
    def on_extended_handshake(self, data: bytes): ...
    def on_metadata(self, data: bytes): ...
    def set_metadata(self): ...
    def next(self, count: int | None = ...): ...
    def add_request(self, block: tuple[int, int]): ...
    def remove_request(self, block: tuple[int, int]): ...
    def reset(self): ...
    def release(self): ...
    def handshake(self): ...
    def keep_alive(self): ...
    def choke(self): ...
    def unchoke(self): ...
    def interested(self): ...
    def not_interested(self): ...
    def have(self, index: int): ...
    def request(self, index: int, begin: int = ..., length: int = ...): ...
    def extended_handshake(self): ...
    def request_metadata(self, piece: int): ...
    def extended(self, extended: int, payload: bytes | str): ...
    def is_alive(
        self, timeout: float = ..., schedule: bool = ...
    ) -> Callable[[], None]: ...
    def _metadata_pieces(self) -> int: ...

class TorrentClient(StreamClient):
    def peer(
        self,
        task: TorrentTask,
        host: str,
        port: int,
        ssl: bool = ...,
        connection: TorrentConnection | None = ...,
    ) -> TorrentConnection: ...
    def on_connect(self, connection: Connection): ...
    def on_acquire(self, connection: Connection): ...
    def on_data(self, connection: Connection, data: bytes): ...
    def build_connection(  # type: ignore[override]
        self,
        socket: Socket,
        address: tuple[str, int] | str | None,
        ssl: bool = ...,
    ) -> TorrentConnection: ...
