"""
This type stub file was generated by pyright.
"""

from . import address, allow, base, deny, dummy, memory, passwd, simple
from .address import AddressAuth
from .allow import AllowAuth
from .base import Auth
from .deny import DenyAuth
from .dummy import DummyAuth
from .memory import MemoryAuth
from .passwd import PasswdAuth
from .simple import SimpleAuth

__version__ = ...
__revision__ = ...
__date__ = ...
__copyright__ = ...
__license__ = ...
