import netius.auth.base
import netius.auth.base as base

from typing import PathLike, Any, Dict

class PasswdAuth(netius.auth.base.Auth):
    def __init__(self, path: PathLike[str] | None = ..., *args, **kwargs) -> None: ...
    @classmethod
    def auth(cls, username: str, password: str, path: str = ..., *args, **kwargs) -> bool: ...
    @classmethod
    def get_passwd(cls, path: PathLike[str], cache: bool = ...) -> (Any | Dict): ...
    def auth_i(self, username: str, password: str, *args, **kwargs) -> bool: ...
