from netius import Auth

class AddressAuth(Auth):
    def __init__(self, allowed: list[str] = ..., *args, **kwargs) -> None: ...
    @classmethod
    def auth(cls, allowed: list[str] = ..., *args, **kwargs) -> bool: ...
