from netius import Auth

class AddressAuth(Auth):
    def __init__(self, allowed: list[str] = ..., *args, **kwargs) -> None: ...
    @classmethod
    def auth(cls, allowed: list[str] = ..., *args, **kwargs) -> bool: ...
    @classmethod
    def is_simple(cls) ->  bool: ...
    def auth_i(self, *args, **kwargs) -> bool: ...
