from typing import Any

from netius import Base, Connection, Observable, Protocol

class Agent(Observable):
    _container_loop: Base | None

    @property
    def name(self) -> str: ...
    @property
    def connections(self) -> list[Connection]: ...
    @classmethod
    def cleanup_s(cls): ...
    def cleanup(self, destroy: bool = ...): ...
    def destroy(self): ...
    def load(self): ...
    def unload(self): ...
    def ticks(self): ...
    def on_start(self): ...
    def on_stop(self): ...
    def connections_dict(
        self, full: bool = ..., parent: bool = ...
    ) -> dict[str, Any]: ...
    def info_dict(self, full: bool = ...) -> dict[str, Any]: ...

class ClientAgent(Agent):
    _clients: dict[int | None, ClientAgent]

    @classmethod
    def cleanup_s(cls): ...
    @classmethod
    def get_client_s(cls, *args, **kwargs) -> ClientAgent: ...
    def connect(
        self, host: str, port: int, ssl: bool = ..., *args, **kwargs
    ) -> Protocol: ...
    def _relay_protocol_events(self, protocol: Protocol): ...

class ServerAgent(Agent):
    pass
