from types import ModuleType
from typing import Any, Callable, Coroutine, Generator

from netius.base import async_old

class Future(async_old.Future):
    def __iter__(self) -> Generator[Future, Any, Any]: ...
    def __await__(self) -> Generator[Future, Any, Any]: ...

class AwaitWrapper:
    _is_generator: bool
    generator: Any
    is_generator: bool

    def __init__(self, generator: Any, generate: bool = ...): ...
    def __await__(self) -> Generator[Any, Any, Any]: ...
    def __iter__(self) -> AwaitWrapper: ...
    def __next__(self) -> Any: ...
    def next(self) -> Any: ...
    def generate(self, value: Any) -> Generator[Any, Any, None]: ...
    def _await_generator(self) -> Generator[Any, Any, Any]: ...
    def _await_basic(self) -> Generator[Any, Any, Any]: ...

class CoroutineWrapper:
    coroutine: Coroutine[Any, Any, Any]

    def __init__(self, coroutine: Coroutine[Any, Any, Any]): ...
    def __iter__(self) -> CoroutineWrapper: ...
    def __next__(self) -> Any: ...
    def next(self) -> Any: ...
    def restore(self, value: Any): ...

def coroutine(function: Callable[..., Any]) -> Callable[..., AwaitWrapper]: ...
def ensure_generator(value: Any) -> tuple[bool, Any]: ...
def get_asyncio() -> ModuleType | None: ...
def is_coroutine(callable: Callable[..., Any]) -> bool: ...
def is_coroutine_object(generator: Any) -> bool: ...
def is_coroutine_native(generator: Any) -> bool: ...
def is_future(future: Any) -> bool: ...
def _sleep(timeout: float, compat: bool = ...) -> Generator[Future, Any, Any]: ...
def _wait(
    event: str, timeout: float | None = ..., future: Future | None = ...
) -> Generator[Future, Any, Any]: ...
def sleep(*args, **kwargs) -> AwaitWrapper: ...
def wait(*args, **kwargs) -> AwaitWrapper: ...
def coroutine_return(coroutine: Any) -> AwaitWrapper: ...
def _coroutine_return(coroutine: Any) -> Generator[Any, Any, Any]: ...
