from typing import Any, Callable, Generator

from netius.base.common import AbstractBase

class Future:
    _asyncio_future_blocking: bool
    status: int
    done_callbacks: list[Callable[[Future], Any]]
    partial_callbacks: list[Callable[[Future, Any], Any]]
    ready_callbacks: list[Callable[[], bool]]
    closed_callbacks: list[Callable[[], bool]]

    def __init__(self, loop: Any = ...): ...
    def __iter__(self) -> Generator[Future, Any, None]: ...
    def cleanup(self): ...
    def running(self) -> bool: ...
    def done(self) -> bool: ...
    def cancelled(self) -> bool: ...
    def finished(self) -> bool: ...
    def result(self) -> Any: ...
    def exception(self, timeout: float | None = ...) -> BaseException | None: ...
    def partial(self, value: Any): ...
    def add_done_callback(self, function: Callable[[Future], Any]): ...
    def add_partial_callback(self, function: Callable[[Future, Any], Any]): ...
    def add_ready_callback(self, function: Callable[[], bool]): ...
    def add_closed_callback(self, function: Callable[[], bool]): ...
    def remove_done_callback(self, function: Callable[[Future], Any]): ...
    def remove_partial_callback(self, function: Callable[[Future, Any], Any]): ...
    def remove_ready_callback(self, function: Callable[[], bool]): ...
    def remove_closed_callback(self, function: Callable[[], bool]): ...
    def approve(self, cleanup: bool = ...): ...
    def cancel(self, cleanup: bool = ..., force: bool = ...) -> bool: ...
    def set_result(self, result: Any, cleanup: bool = ..., force: bool = ...): ...
    def set_exception(
        self, exception: BaseException, cleanup: bool = ..., force: bool = ...
    ): ...
    @property
    def ready(self) -> bool: ...
    @property
    def closed(self) -> bool: ...
    def _done_callbacks(self, cleanup: bool = ..., delayed: bool = ...) -> Any: ...
    def _partial_callbacks(self, value: Any, delayed: bool = ...) -> Any: ...
    def _wrap(self, future: Future): ...
    def _delay(self, callable: Callable[[], Any]) -> Any: ...

class Task(Future):
    def __init__(self, future: Future | None = ...): ...

class Handle:
    def __init__(self, callable_t: tuple[Any, ...] | None = ...): ...
    def cancel(self): ...

class Executor:
    def submit(self, callable: Callable[..., Any], *args, **kwargs) -> Future: ...

class ThreadPoolExecutor(Executor):
    owner: AbstractBase

    def __init__(self, owner: AbstractBase): ...
    def submit(self, callable: Callable[..., Any], *args, **kwargs) -> Future: ...

def coroutine(function: Callable[..., Any]) -> Callable[..., Any]: ...
def async_test_all(
    factory: Callable[..., Any] | None = ..., close: bool = ...
) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
def async_test(function: Callable[..., Any]) -> Callable[..., Any]: ...
def ensure_generator(value: Any) -> tuple[bool, Any]: ...
def get_asyncio(): ...
def is_coroutine(callable: Callable[..., Any]) -> bool: ...
def is_coroutine_object(generator: Any) -> bool: ...
def is_coroutine_native(generator: Any) -> bool: ...
def is_future(future: Any) -> bool: ...
def is_neo() -> bool: ...
def is_asynclib() -> bool: ...
def is_await() -> bool: ...
def wakeup(force: bool = ...): ...
def sleep(
    timeout: float, compat: bool = ..., future: Future | None = ...
) -> Generator[Future, Any, None]: ...
def wait(
    event: str, timeout: float | None = ..., future: Future | None = ...
) -> Generator[Future, Any, None]: ...
def notify(event: str, data: Any = ...): ...
def coroutine_return(coroutine: Any) -> Generator[Any, Any, None]: ...
