from collections import deque
from socket import socket as Socket
from threading import RLock
from typing import Any, Callable

from netius import BaseThread, Connection, Request, Response
from netius.base.common import AbstractBase
from netius.base.common import *
from netius.base.conn import *
from netius.pool import EventFile

BUFFER_SIZE: int | None
GC_TIMEOUT: float

class Client(AbstractBase):
    _client: Client | None
    receive_buffer: int | None
    send_buffer: int | None
    thread: bool
    daemon: bool

    def __init__(self, thread: bool = ..., daemon: bool = ..., *args, **kwargs): ...
    @classmethod
    def get_client_s(cls, *args, **kwargs) -> Client: ...
    @classmethod
    def cleanup_s(cls): ...
    def ensure_loop(self, env: bool = ...): ...
    def join(self, timeout: float | None = ...): ...

class DatagramClient(Client):
    socket: Socket | None
    renable: bool
    wready: bool
    pending_s: int
    pending: deque[tuple[Any, Any]]
    requests: list[Request]
    requests_m: dict[int, Request]
    pending_lock: RLock

    def __init__(self, *args, **kwargs): ...
    def boot(self): ...
    def cleanup(self): ...
    def on_read(self, _socket: Socket | EventFile): ...
    def on_write(self, _socket: Socket | EventFile): ...
    def on_error(self, _socket: Socket | EventFile): ...
    def on_exception(self, exception: BaseException): ...  # type: ignore[override]
    def on_expected(self, exception: BaseException): ...  # type: ignore[override]
    def on_data(self, connection: Any, data: bytes): ...
    def keep_gc(self, timeout: float = ..., run: bool = ...): ...
    def gc(self, callbacks: bool = ...): ...
    def add_request(self, request: Request): ...
    def remove_request(self, request: Request): ...
    def get_request(self, id: int | Response) -> Request | None: ...
    def ensure_socket(self): ...
    def ensure_write(self): ...
    def remove_write(self): ...
    def enable_read(self): ...
    def disable_read(self): ...
    def send(
        self,
        data: bytes | str,
        address: Any,
        delay: bool = ...,
        ensure_loop: bool = ...,
        callback: Callable[[DatagramClient], Any] | None = ...,
    ): ...
    def _send(self, _socket: Socket): ...
    def _flush_write(self): ...

class StreamClient(Client):
    pendings: list[Connection]
    free_map: dict[tuple[Any, ...], list[Connection]]

    def __init__(self, *args, **kwargs): ...
    def cleanup(self): ...
    def ticks(self): ...
    def info_dict(self, full: bool = ...) -> dict[str, Any]: ...
    def acquire_c(
        self,
        host: str,
        port: int | str,
        ssl: bool = ...,
        key_file: str | None = ...,
        cer_file: str | None = ...,
        validate: bool = ...,
        callback: Callable[..., Any] | None = ...,
    ) -> Connection: ...
    def release_c(self, connection: Connection): ...
    def remove_c(self, connection: Connection): ...
    def validate_c(self, connection: Connection, close: bool = ...) -> bool: ...
    def connect(  # type: ignore[override]
        self,
        host: str,
        port: int | str,
        ssl: bool = ...,
        key_file: str | None = ...,
        cer_file: str | None = ...,
        ca_file: str | None = ...,
        ca_root: bool = ...,
        ssl_verify: bool = ...,
        family: int = ...,
        type: int = ...,
        ensure_loop: bool = ...,
        env: bool = ...,
    ) -> Connection: ...
    def acquire(self, connection: Connection): ...
    def on_read(self, _socket: Socket | EventFile): ...
    def on_write(self, _socket: Socket | EventFile): ...
    def on_error(self, _socket: Socket | EventFile): ...
    def on_exception(self, exception: BaseException, connection: Connection): ...
    def on_expected(self, exception: BaseException, connection: Connection): ...
    def on_connect(self, connection: Connection): ...
    def on_upgrade(self, connection: Connection): ...
    def on_ssl(self, connection: Connection): ...
    def on_acquire(self, connection: Connection): ...
    def on_release(self, connection: Connection): ...
    def on_data(self, connection: Connection, data: bytes): ...
    def _connectf(self, connection: Connection): ...
    def _connects(self): ...
    def _connect(self, connection: Connection): ...
    def _ssl_handshake(self, connection: Connection): ...
