import netius as netius
import netius.base.async_old as async_old
import netius.base.asynchronous as asynchronous
import netius.base.common
import netius.base.compat as compat
import netius.base.config as config
import netius.base.errors as errors
import netius.base.legacy as legacy
import netius.base.log as log
import netius.base.observer as observer
import netius.base.request as request
import netius.base.tls as tls
import netius.base.util as util
import netius.middleware as middleware
import socket
from _typeshed import Incomplete
from netius.base.async_neo import (
    AwaitWrapper as AwaitWrapper,
    CoroutineWrapper as CoroutineWrapper,
    Future as Future,
    coroutine as coroutine,
    coroutine_return as coroutine_return,
    ensure_generator as ensure_generator,
    get_asyncio as get_asyncio,
    is_coroutine as is_coroutine,
    is_coroutine_native as is_coroutine_native,
    is_coroutine_object as is_coroutine_object,
    is_future as is_future,
    sleep as sleep,
    wait as wait,
)
from netius.base.async_old import (
    Executor as Executor,
    Handle as Handle,
    Task as Task,
    ThreadPoolExecutor as ThreadPoolExecutor,
    async_test as async_test,
    async_test_all as async_test_all,
    is_asynclib as is_asynclib,
    is_await as is_await,
    is_neo as is_neo,
    notify as notify,
    wakeup as wakeup,
)
from netius.base.common import (
    AbstractBase as AbstractBase,
    Base as Base,
    BaseThread as BaseThread,
    DiagBase as DiagBase,
    build_future as build_future,
    compat_loop as compat_loop,
    ensure as ensure,
    ensure_asyncio as ensure_asyncio,
    ensure_loop as ensure_loop,
    ensure_main as ensure_main,
    ensure_pool as ensure_pool,
    get_event_loop as get_event_loop,
    get_loop as get_loop,
    get_main as get_main,
    get_poll as get_poll,
    new_loop as new_loop,
    new_loop_asyncio as new_loop_asyncio,
    new_loop_main as new_loop_main,
    stop_loop as stop_loop,
)
from netius.base.conn import (
    BaseConnection as BaseConnection,
    Connection as Connection,
    DiagConnection as DiagConnection,
)
from netius.base.poll import (
    EpollPoll as EpollPoll,
    KqueuePoll as KqueuePoll,
    Poll as Poll,
    PollPoll as PollPoll,
    SelectPoll as SelectPoll,
)
from typing import Any, Self

BUFFER_SIZE: None
GC_TIMEOUT: float

class Client(netius.base.common.AbstractBase):
    def __init__(self, thread: bool = ..., daemon: bool = ..., *args, **kwargs) -> None: ...
    @classmethod
    def get_client_s(cls, *args, **kwargs) -> Self@Client: ...
    @classmethod
    def cleanup_s(cls) -> None: ...
    def ensure_loop(self, env: bool = ...) -> None: ...
    def join(self, timeout: Any | None = ...) -> None: ...

class DatagramClient(Client):
    def __init__(self, *args, **kwargs) -> None: ...
    def boot(self) -> None: ...
    def cleanup(self) -> None: ...
    def on_read(self, _socket: Any) -> None: ...
    def on_write(self, _socket: Any) -> None: ...
    def on_error(self, _socket: Any) -> None: ...
    def on_exception(self, exception: Any) -> None: ...
    def on_expected(self, exception: Any) -> None: ...
    def on_data(self, connection: Any, data: Any) -> None:  ...
    def keep_gc(self, timeout: float = ..., run: bool = ...) -> None: ...
    def gc(self, callbacks: bool = ...) -> None: ...
    def add_request(self, request: Any) -> None: ...
    def remove_request(self, request: Any) -> None: ...
    def get_request(self, id: Any) -> Any: ...
    def ensure_socket(self) -> None: ...
    def ensure_write(self) -> None: ...
    def remove_write(self) -> None: ...
    def enable_read(self) -> None: ...
    def disable_read(self) -> None: ...
    def send(self, data: Any, address: Any, delay: bool = ..., ensure_loop: bool = ..., callback: Any | None = ...) -> None : ...
    def _send(self, _socket: Any) -> None: ...
    def _flush_write(self) -> None: ...

class StreamClient(Client):
    def __init__(self, *args, **kwargs) -> None: ...
    def cleanup(self) -> None: ...
    def ticks(self) -> None: ...
    def info_dict(self, full: bool = ...) -> None: ...
    def acquire_c(
        self,
        host: Any,
        port: Any,
        ssl: bool = False,
        key_file: Any | None = None,
        cer_file: Any | None = None,
        validate: bool = False,
        callback: Any | None = None
    ) -> Any : ...
    def release_c(self, connection: Any) -> None: ...
    def remove_c(self, connection: Any) -> None: ...
    def validate_c(self, connection: Any, close: bool = ...) -> Any: ...
    def connect(
        self,
        host: Any,
        port: Any,
        ssl: bool = ...,
        key_file: Any | None = ...,
        cer_file: Any | None = ...,
        ca_file: Any | None = ...,
        ca_root: bool = ...,
        ssl_verify: bool = ...,
        family: Any = ...,
        type: Any = ...,
        ensure_loop: bool = ...,
        env: bool = ...
    ) -> Any: ...
    def acquire(self, connection: Any) -> None: ...
    def on_read(self, _socket: Any) -> None: ...
    def on_write(self, _socket: Any) -> None: ...
    def on_error(self, _socket: Any) -> None: ...
    def on_exception(self, exception: Any, connection: Any) -> None: ...
    def on_expected(self, exception: Any, connection: Any) -> None: ...
    def on_connect(self, connection: Any) -> None: ...
    def on_upgrade(self, connection: Any) -> None: ...
    def on_ssl(self, connection: Any) -> None: ...
    def on_acquire(self, connection: Any) -> None: ...
    def on_release(self, connection: Any) -> None: ...
    def on_data(self, connection: Any, data: Any) -> None: ...
    def _connectf(self, connection: Any) -> None: ...
    def _connects(self) -> None: ...
    def _connect(self, connection: Any) -> None: ...
    def _ssl_handshake(self, connection: Any) -> None: ...
