import netius as netius
import netius.base.async_old as async_old
import netius.base.asynchronous as asynchronous
import netius.base.compat as compat
import netius.base.config as config
import netius.base.errors as errors
import netius.base.legacy as legacy
import netius.base.log as log
import netius.base.observer
import netius.base.observer as observer
import netius.base.tls as tls
import netius.base.util as util
import netius.middleware as middleware
import signal
import socket
import ssl
import threading
from netius.base.async_neo import (
    AwaitWrapper as AwaitWrapper,
    CoroutineWrapper as CoroutineWrapper,
    Future as Future,
    coroutine as coroutine,
    coroutine_return as coroutine_return,
    ensure_generator as ensure_generator,
    get_asyncio as get_asyncio,
    is_coroutine as is_coroutine,
    is_coroutine_native as is_coroutine_native,
    is_coroutine_object as is_coroutine_object,
    is_future as is_future,
    sleep as sleep,
    wait as wait,
)
from netius.base.async_old import (
    Executor as Executor,
    Handle as Handle,
    Task as Task,
    ThreadPoolExecutor as ThreadPoolExecutor,
    async_test as async_test,
    async_test_all as async_test_all,
    is_asynclib as is_asynclib,
    is_await as is_await,
    is_neo as is_neo,
    notify as notify,
    wakeup as wakeup,
)
from netius.base.conn import (
    BaseConnection as BaseConnection,
    Connection as Connection,
    DiagConnection as DiagConnection,
)
from netius.base.poll import (
    EpollPoll as EpollPoll,
    KqueuePoll as KqueuePoll,
    Poll as Poll,
    PollPoll as PollPoll,
    SelectPoll as SelectPoll,
)

from typing import Any, ClassVar, LiteralString

NAME: str
VERSION: str
PLATFORM: str
IDENTIFIER_TINY: str
IDENTIFIER_SHORT: str
IDENTIFIER_LONG: str
WSAEWOULDBLOCK: int
WSAECONNABORTED: int
WSAECONNRESET: int
SSL_ERROR_CERT_ALREADY_IN_HASH_TABLE: int
POOL_ORDER: list[Poll]
SILENT_ERRORS: list[int]
VALID_ERRORS: list[int]
SSL_SILENT_ERRORS: list[int]
SSL_VALID_ERRORS: list[int]
SSL_ERROR_NAMES: list[str]
SSL_VALID_REASONS: tuple[str]
TCP_TYPE: int
UDP_TYPE: int
STATE_STOP: int
STATE_START: int
STATE_PAUSE: int
STATE_CONFIG: int
STATE_POLL: int
STATE_TICK: int
STATE_READ: int
STATE_WRITE: int
STATE_ERRROR: int
STATE_STRINGS: tuple[str]
KEEPALIVE_TIMEOUT: int
KEEPALIVE_INTERVAL: int
KEEPALIVE_COUNT: int
ALLOW_BLOCK: bool
LOG_FORMAT: str
BASE_PATH: str
EXTRAS_PATH: str
SSL_KEY_PATH: str
SSL_CER_PATH: str
SSL_CA_PATH: str
SSL_DH_PATH: str

class AbstractBase(netius.base.observer.Observable):
    def __init__(
        self,
        name: Any | None = ...,
        handlers: Any | None = ...,
        *args,
        **kwargs
    ) -> None: ...
    @classmethod
    def test_poll(cls, preferred: Any | None = ...) -> (type[EpollPoll] | type[KqueuePoll] | type[PollPoll] | type[SelectPoll]) -> None: ...
    @classmethod
    def get_loop(cls, compat: bool = ..., asyncio: bool = ...) -> (Any | None) -> None: ...
    @classmethod
    def get_main(cls, compat: bool = ...) -> (Any | None) -> None: ...
    @classmethod
    def get_asyncio(cls) -> (Any | None) -> None: ...
    @classmethod
    def set_main(cls, instance, set_compat: bool = ...) -> None: ...
    @classmethod
    def unset_main(cls, set_compat: bool = ...) -> None: ...
    @classmethod
    def patch_asyncio(cls) -> None: ...
    @classmethod
    def waitpid(cls, pid: Any) -> None: ...
    def destroy(self) -> None: ...
    def call_safe(self, callable, args, kwargs) -> None : ...
    def wait_event(self, callable, name: Any | None = ...) -> None : ...
    def unwait_event(self, callable, name: Any | None = ...) -> None : ...
    def delay(
        self,
        callable: Any,
        timeout: Any | None = ...,
        immediately: bool = ...,
        verify: bool = ...,
        safe: bool = ...
    ) -> (Any | None) : ...
    def delay_s(
        self,
        callable: Any,
        timeout: Any | None = ...,
        immediately: bool = ...,
        verify: bool = ...,
        wakeup: bool = ...
    ) -> None : ...
    def delay_m(self) -> None: ...
    def ensure(
        self,
        coroutine: Any,
        args,
        kwargs,
        thread: Any | None = ...,
        future: Any | None = ...,
        immediately: bool = ...
    ) -> (Any | Future) -> None: ...
    def resolve_hostname(self, hostname: Any, type: str = ...) -> Future: ...
    def run_forever(self) -> None: ...
    def run_coroutine(self, coroutine: Any, args, kwargs, thread: Any | None = ..., close: Any | None = ...) -> (Any | None) -> None: ...
    def wakeup(self, force: bool = ...) -> None: ...
    def sleep(self, timeout: Any, future: Any | None = ...) -> (Any | Future) -> None: ...
    def wait(self, event: Any, timeout: Any | None = ..., future: Any | None = ...) -> (Any | Future) -> None: ...
    def notify(self, event, data: Any | None = ...) -> None: ...
    def load(self, full: bool = ...) -> None: ...
    def unload(self, full: bool = ...) -> None: ...
    def boot(self) -> None: ...
    def welcome(self) -> None: ...
    def load_logging(self, level: int = ..., format: str = ..., unique: bool = ...) -> None: ...
    def unload_logging(self, safe: bool = ...) -> None: ...
    def extra_logging(self, level: Any, formatter: Any) -> None: ...
    def level_logging(self, level: Any) -> None: ...
    def load_diag(self, env: bool = ...) -> None: ...
    def load_middleware(self, suffix: str = ...) -> None: ...
    def unload_middleware(self) -> None: ...
    def register_middleware(self, middleware_c: Any, *args, **kwargs) -> None: ...
    def call_middleware(self, name, *args, **kwargs) -> None: ...
    def bind_signals(self, signals: Any = (signal.SIGINT, signal.SIGTERM, signal.SIGHUP if hasattr(signal, "SIGHUP") else None, signal.SIGQUIT if hasattr(signal, "SIGQUIT") else None), handler: Any | None = ...) -> None: ...
    def unbind_signals(self, signals: Any = (signal.SIGINT, signal.SIGTERM, signal.SIGHUP if hasattr(signal, "SIGHUP") else None, signal.SIGQUIT if hasattr(signal, "SIGQUIT") else None)) -> None: ...
    def bind_env(self) -> None: ...
    def forever(self, env: bool = ...) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def close(self) -> None: ...
    def finish(self) -> None: ...
    def main(self) -> None: ...
    def is_main(self) -> bool: ...
    def is_running(self) -> bool: ...
    def is_started(self) -> bool: ...
    def is_stopped(self) -> bool: ...
    def is_paused(self) -> bool: ...
    def is_edge(self) -> bool: ...
    def is_empty(self) -> bool: ...
    def is_sub_read(self, socket: Any) -> bool: ...
    def is_sub_write(self, socket: Any) -> bool: ...
    def is_sub_error(self, socket: Any) -> bool: ...
    def sub_all(self, socket: Any) -> None: ...
    def unsub_all(self, socket: Any) -> None: ...
    def sub_read(self, socket: Any) -> None: ...
    def sub_write(self, socket: Any) -> None: ...
    def sub_error(self, socket: Any) -> None: ...
    def unsub_read(self, socket: Any) -> None: ...
    def unsub_write(self, socket: Any) -> None: ...
    def unsub_error(self, socket: Any) -> None: ...
    def cleanup(self, destroy: bool = ...) -> None: ...
    def loop(self) -> None: ...
    def block(self) -> None: ...
    def fork(self, timeout: int = ...) -> None: ...
    def finalize(self) -> None: ...
    def ticks(self) -> None: ...
    def reads(self, reads: Any, state: bool = ...) -> None: ...
    def writes(self, writes: Any, state: bool = ...) -> None: ...
    def errors(self, errors: Any, state: bool = ...) -> None: ...
    def datagram(
        self,
        family: Any = ...,
        type: Any = ...,
        local_host: Any | None = ...,
        local_port: Any | None = ...,
        remote_host: Any | None = ...,
        remote_port: Any | None = ...,
        callback: Any | None = ...
    ) -> Connection: ...
    def connect(
        self,
        host: Any,
        port: Any,
        receive_buffer: Any | None = ...,
        send_buffer: Any | None = ...,
        ssl: bool = ...,
        key_file: Any | None = ...,
        cer_file: Any | None = ...,
        ca_file: Any | None = ...,
        ca_root: bool = ...,
        ssl_verify: bool = ...,
        family: Any = ...,
        type: Any = ...,
        callback: Any | None = ...,
        env: bool = ...
    ) -> Any: ...
    def acquire(self, connection: Any) -> None: ...
    def pregister(self, pool: Any) -> None: ...
    def punregister(self, pool: Any) -> None: ...
    def pcallback(self, event: Any, socket: Any, pool: Any) -> None: ...
    def nensure(self) -> None: ...
    def nstart(self) -> None: ...
    def nstop(self) -> None: ...
    def tensure(self) -> None: ...
    def tstart(self) -> None: ...
    def tstop(self) -> None: ...
    def texecute(
        self,
        callable: Any,
        args: ...,
        kwargs: ...,
        callback: Any | None = ...,
    ) -> None: ...
    def files(self) -> None: ...
    def fopen(self, *args, **kwargs) -> None: ...
    def fclose(self, *args, **kwargs) -> None: ...
    def fread(self, *args, **kwargs) -> None: ...
    def fwrite(self, *args, **kwargs) -> None: ...
    def fensure(self) -> None: ...
    def fstart(self) -> None: ...
    def fstop(self) -> None: ...
    def on_connection_c(self, connection: Any) -> None: ...
    def on_connection_d(self, connection: Any) -> None: ...
    def on_stream_c(self, stream: Any) -> None: ...
    def on_stream_d(self, stream: Any) -> None: ...
    def on_fork(self) -> None: ...
    def on_join(self) -> None: ...
    def on_child(self, pipe: Any | None = ...) -> None: ...
    def on_command(self, command: Any) -> None: ...
    def on_diag(self) -> None: ...
    def on_start(self) -> None: ...
    def on_stop(self) -> None: ...
    def on_pause(self) -> None: ...
    def on_resume(self) -> None: ...
    def on_read(self, _socket: Any) -> None: ...
    def on_write(self, _socket: Any) -> None: ...
    def on_error(self, _socket: Any) -> None: ...
    def on_exception(self, exception: Any, connection: Any) -> None: ...
    def on_expected(self, exception: Any, connection: Any) -> None: ...
    def on_connect(self, connection: Any) -> None: ...
    def on_upgrade(self, connection: Any) -> None: ...
    def on_client_ssl(self, connection: Any) -> None: ...
    def on_acquire(self, connection: Any) -> None: ...
    def on_acquire_base(self, connection: Any) -> None: ...
    def on_release(self, connection: Any) -> None: ...
    def on_release_base(self, connection: Any) -> None: ...
    def on_data(self, connection: Any, data: Any) -> None: ...
    def on_data_base(self, connection: Any, data: Any) -> None: ...
    def info_dict(self, full: bool = ...) -> None: ...
    def info_string(self, full: bool = ..., safe: bool = ...) -> None: ...
    def connections_dict(self, full: bool = ...) -> None: ...
    def connection_dict(self, id, full: bool = ...) -> None: ...
    def build_connection(
        self,
        socket: Any,
        address: Any | None = ...,
        datagram: bool = ...,
        ssl: bool = ...
    ) -> Connection: ...
    def base_connection(self, *args, **kwargs) -> base_connection: ...
    def new_connection(self, connection: Connection) -> None: ...
    def del_connection(self, connection: Connection) -> None: ...
    def add_callback(self, socket: Any, callback: Any) -> None: ...
    def remove_callback(self, socket: Any, callback: Any) -> None: ...
    def load_config(self, path: str = ..., **kwargs) -> None: ...
    def apply_config(self, path: str, kwargs) -> dict: ...
    def exec_safe(self, connection: Connection, callable: Any, *args, **kwargs) -> Any: ...
    def is_devel(self) -> bool: ...
    def is_debug(self) -> bool: ...
    def is_info(self) -> bool: ...
    def is_warning(self) -> bool: ...
    def is_error(self) -> bool: ...
    def is_critical(self) -> bool: ...
    def debug(self, object: Any) -> None: ...
    def info(self, object: Any) -> None: ...
    def warning(self, object: Any) -> None: ...
    def error(self, object: Any) -> None: ...
    def critical(self, object: Any) -> None: ...
    def log_stack(self, method: Any | None = ..., info: bool = ...) -> None: ...
    def log_info(self, method: Any | None = ...) -> None: ...
    def log(self, *args, **kwargs) -> None: ...
    def log_python_3(self, object: Any, level: int = ...) -> None: ...
    def log_python_2(self, object: Any, level: int = ...) -> None: ...
    def build_poll(self) -> (Any | EpollPoll | KqueuePoll | PollPoll | SelectPoll): ...
    def build_future(self, compat: bool = ..., asyncio: bool = ...) -> Future: ...
    def get_id(self, unique: bool = ...) -> Any: ...
    def get_poll(self) -> (Any | EpollPoll | KqueuePoll | PollPoll | SelectPoll): ...
    def get_poll_name(self) -> str: ...
    def get_state(self) -> Any: ...
    def set_state(self, state: int) -> None: ...
    def get_state_s(self, lower: bool = ...) -> Any: ...
    def get_env(
        self,
        name: Any,
        default: Any | None = ...,
        cast: Any | None = ...,
        expand: bool = ...
    ) -> (Any | str | None): ...
    def expand(self, value: Any, encoding: str = ..., force: bool = ...) -> None: ...
    def get_protocols(self) -> None: ...
    def get_adapter(self, name: str = ..., *args, **kwargs) -> Any: ...
    def get_auth(self, name: str = ..., *args, **kwargs) -> Any: ...
    def get_connection(self, socket: Any) -> Connection: ...
    def _pending(self, connection: Connection) -> Any: ...
    def _notifies(self) -> int: ...
    def _delays(self) -> None: ...
    def _generate(self, hashed: bool = ...) -> str: ...
    def _connect(self, connection: Connection) -> None: ...
    def _connectf(self, connection: Connection) -> None: ...
    def _socket_keepalive(
        self,
        _socket: Any,
        timeout: Any | None = ...,
        interval: Any | None = ...,
        count: Any | None = ...
    ) -> None: ...
    def _ssl_init(self, strict: bool = ..., env: bool = ...) -> None: ...
    def _ssl_destroy(self) -> None: ...
    def _ssl_callback(self, socket: Any, hostname: Any, context: Any) -> None: ...
    def _ssl_ctx(
        self,
        values,
        context: Any | None = ...,
        secure: int = ...,
        context_options: list = ...,
    ) -> Any: ...
    def _ssl_ctx_base(self, context: Any, secure: int = ..., context_options: list = ...) -> None: ...
    def _ssl_ctx_protocols(self, context: Any) -> None: ...
    def _ssl_ctx_alpn(self, context: Any) -> None: ...
    def _ssl_ctx_npn(self, context: Any) -> None: ...
    def _ssl_certs(
        self,
        context: Any,
        key_file: Any | None = ...,
        cer_file: Any | None = ...,
        ca_file: Any | None = ...,
        ca_root: bool = False,
        verify_mode: Any = ...,
        check_hostname: bool = ...
    ) -> None: ...
    def _ssl_upgrade(
        self,
        _socket: Any,
        key_file: Any | None = ...,
        cer_file: Any | None = ...,
        ca_file: Any | None = ...,
        ca_root: bool = ...,
        server: bool = ...,
        ssl_verify: bool = ...,
        server_hostname: Any | None = ...,
    ) -> Any: ...
    def _ssl_wrap(
        self,
        _socket: Any,
        key_file: Any | None = ...,
        cer_file: Any | None = ...,
        ca_file: Any | None = ...,
        ca_root: bool = ...,
        server: bool = ...,
        ssl_verify: bool = ...,
        server_hostname: Any | None = ...
    ) -> Any: ...
    def _ssl_handshake(self, connection: Connection) -> None: ...
    def _ssl_client_handshake(self, connection: Connection) -> None: ...
    def _expand_destroy(self) -> None: ...
    def _level(self, level: Any) -> (Any | int): ...
    def _format_delta(self, time_delta, count: int = ...)  -> (LiteralString | Any): ...
    def _wait_forever(self, sleep: int = ...) -> None: ...
    @property
    def is_parent(self) -> bool: ...
    @property
    def is_child(self) -> bool: ...
    @property
    def is_forked(self) -> bool: ...

class DiagBase(AbstractBase):
    def __init__(self, *args, **kwargs) -> None: ...
    def reads(self, *args, **kwargs) -> None: ...
    def writes(self, *args, **kwargs) -> None: ...
    def errors(self, *args, **kwargs) -> None: ...
    def info_dict(self, full: bool = ...) -> dict[str, int]: ...

class BaseThread(threading.Thread):
    def __init__(self, owner: Any | None = ..., daemon: bool = ..., *args, **kwargs) -> None: ...
    def run(self) -> None: ...

def new_loop_main(factory: Any | None = ..., _compat: Any | None = ..., **kwargs) -> (CompatLoop | Any | AbstractBase | DiagBase): ...
def new_loop_asyncio(**kwargs) -> (Any | None): ...
def new_loop(factory: Any | None = ..., _compat: Any | None = ..., asyncio: Any | None = ..., **kwargs) -> (Any | CompatLoop | AbstractBase | DiagBase | None): ...
def ensure_main(factory: Any | None = ..., **kwargs) -> None: ...
def ensure_asyncio(**kwargs) -> None: ...
def ensure_loop(factory: Any | None = ..., asyncio: Any | None = ..., **kwargs) -> None: ...
def get_main(factory: Any | None = ..., ensure: bool = ..., **kwargs) -> (Any | None): ...
def get_loop(
    factory: Any | None = ...,
    ensure: bool = ...,
    _compat: Any | None = ...,
    asyncio: Any | None = ...,
    **kwargs: Any
) -> (Any | None): ...
def get_event_loop(*args, **kwargs) -> (Any | None): ...
def stop_loop(compat: bool = ..., asyncio: bool = ...) -> None: ...
def compat_loop(loop: Any) -> Any: ...
def get_poll() -> Any: ...
def build_future(compat: bool = ..., asyncio: bool = ...) -> (Any | None): ...
def ensure(coroutine: Any, args, kwargs, thread: Any | None = ...) -> Any: ...
def ensure_pool(coroutine: Any, args, kwargs) -> Any: ...
