from asyncio import AbstractEventLoop
from collections import deque
from datetime import timedelta
from logging import Formatter, Handler, Logger, StreamHandler
from socket import socket
from ssl import SSLContext, SSLError, SSLObject, SSLSocket, VerifyMode
from threading import RLock, Thread
from types import FrameType
from typing import Any, Callable, Mapping, Sequence
from uuid import UUID

from netius import (
    Auth,
    BaseAdapter,
    CompatLoop,
    Connection,
    Future,
    LogstashHandler,
    Observable,
    Poll,
    Service,
    Stream,
)
from netius.base.diag import DiagApp
from netius.middleware import Middleware
from netius.pool import EventFile, EventPool, FilePool, NotifyPool, TaskPool

OPEN: int
CLOSED: int
PENDING: int
CHUNK_SIZE: int
REASON_TIMEOUT: str
REASON_CLIENT_EOF: str
REASON_UPSTREAM_ERROR: str
REASON_ERROR: str
REASON_EXPLICIT: str
REASON_UNKNOWN: str
POLL_TIMEOUT: float
BUFFER_SIZE_S: int | None
BUFFER_SIZE_C: int | None
NAME: str
VERSION: str
PLATFORM: str
IDENTIFIER_TINY: str
IDENTIFIER_SHORT: str
IDENTIFIER_LONG: str
IDENTIFIER: str
WSAEWOULDBLOCK: int
WSAECONNABORTED: int
WSAECONNRESET: int
SSL_ERROR_CERT_ALREADY_IN_HASH_TABLE: int
POLL_ORDER: tuple[type[Poll], ...]
SILENT_ERRORS: tuple[int, ...]
VALID_ERRORS: tuple[int, ...]
SSL_SILENT_ERRORS: tuple[int, ...]
SSL_VALID_ERRORS: tuple[int, ...]
SSL_ERROR_NAMES: dict[int, str]
SSL_SILENT_REASONS: tuple[str, ...]
SSL_VALID_REASONS: tuple[str, ...]
SSL_ALL_REASONS: tuple[str, ...]
SSL_ALL_REASONS_L: tuple[str, ...]
TCP_TYPE: int
UDP_TYPE: int
STATE_STOP: int
STATE_START: int
STATE_PAUSE: int
STATE_CONFIG: int
STATE_POLL: int
STATE_TICK: int
STATE_READ: int
STATE_WRITE: int
STATE_ERRROR: int
STATE_STRINGS: tuple[str, ...]
COMPACT_MIN: int
DIAG_CLOSED_MAX: int
KEEPALIVE_TIMEOUT: int
KEEPALIVE_INTERVAL: int
KEEPALIVE_COUNT: int
ALLOW_BLOCK: bool
LOG_FORMAT: str
TRACE_FORMAT: str
BASE_PATH: str
EXTRAS_PATH: str
SSL_KEY_PATH: str
SSL_CER_PATH: str
SSL_CA_PATH: str | None
SSL_DH_PATH: str | None

class AbstractBase(Observable):
    _MAIN: AbstractBase | None
    _MAIN_C: CompatLoop | None
    _DIAG_INSTANCE: AbstractBase | None
    _DIAG_CLOSED: deque[dict[str, Any]]
    name: str
    handler_stream: StreamHandler
    handler_remote: LogstashHandler | None
    handlers: Sequence[Handler]
    level: int | str
    diag: bool
    middleware: Sequence[str]
    children: int
    logger_flush_t: float
    tid: int | None
    tname: str | None
    logger: Logger | None
    logging: Sequence[Mapping[str, Any]] | None
    npool: NotifyPool | None
    tpool: TaskPool | None
    fpool: FilePool | None
    poll_c: type[Poll]
    poll: Poll
    poll_name: str
    poll_timeout: float
    keepalive_timeout: int
    keepalive_interval: int
    keepalive_count: int
    allow_block: bool
    poll_owner: bool
    diag_app: DiagApp | None
    middleware_l: list[Middleware]
    connections: list[Connection]
    connections_m: dict[socket, Connection]
    callbacks_m: dict[
        socket | EventFile, list[Callable[[str, socket | EventFile], Any]]
    ]

    def __init__(
        self,
        name: str | None = ...,
        handlers: Sequence[Handler] | None = ...,
        *args,
        **kwargs
    ): ...
    @classmethod
    def test_poll(cls, preferred: str | None = ...) -> type[Poll]: ...
    @classmethod
    def get_loop(
        cls, compat: bool = ..., asyncio: bool = ...
    ) -> AbstractBase | CompatLoop | AbstractEventLoop | None: ...
    @classmethod
    def get_main(cls, compat: bool = ...) -> AbstractBase | CompatLoop | None: ...
    @classmethod
    def get_asyncio(cls) -> AbstractEventLoop | None: ...
    @classmethod
    def set_main(
        cls,
        instance: AbstractBase | None,
        set_compat: bool = ...,
        set_running: bool = ...,
    ): ...
    @classmethod
    def unset_main(cls, set_compat: bool = ...): ...
    @classmethod
    def patch_asyncio(cls): ...
    @classmethod
    def is_py_task(cls) -> bool: ...
    @classmethod
    def waitpid(cls, pid: int): ...
    def destroy(self): ...
    def call_safe(
        self,
        callable: Callable[..., Any],
        args: Sequence[Any] = ...,
        kwargs: Mapping[str, Any] = ...,
    ) -> Any: ...
    def wait_event(self, callable: Callable[[Any], Any], name: str | None = ...): ...
    def unwait_event(self, callable: Callable[[Any], Any], name: str | None = ...): ...
    def delay(
        self,
        callable: Callable[[], Any],
        timeout: float | None = ...,
        immediately: bool = ...,
        verify: bool = ...,
        safe: bool = ...,
    ) -> tuple[float, int, Callable[[], Any], int, list[bool]] | None: ...
    def delay_s(
        self,
        callable: Callable[[], Any],
        timeout: float | None = ...,
        immediately: bool = ...,
        verify: bool = ...,
        wakeup: bool = ...,
    ): ...
    def interval_s(
        self,
        callable: Callable[[], Any],
        timeout: float | None = ...,
        immediately: bool = ...,
        verify: bool = ...,
        wakeup: bool = ...,
    ): ...
    def unpend(
        self, callable_t: tuple[float, int, Callable[[], Any], int, list[bool]] | None
    ): ...
    def compact(self): ...
    def delay_m(self): ...
    def ensure(
        self,
        coroutine: Any,
        args: Sequence[Any] = ...,
        kwargs: Mapping[str, Any] = ...,
        thread: bool | None = ...,
        future: Future | None = ...,
        immediately: bool = ...,
    ) -> Future: ...
    def resolve_hostname(self, hostname: str, type: str = ...) -> Future: ...
    def run_forever(self): ...
    def run_coroutine(
        self,
        coroutine: Any,
        args: Sequence[Any] = ...,
        kwargs: Mapping[str, Any] = ...,
        thread: bool | None = ...,
        close: bool | None = ...,
    ) -> Any: ...
    def wakeup(self, force: bool = ...): ...
    def sleep(self, timeout: float, future: Future | None = ...) -> Future: ...
    def wait(
        self, event: str, timeout: float | None = ..., future: Future | None = ...
    ) -> Future: ...
    def notify(self, event: str, data: Any = ...): ...
    def load(self, full: bool = ...): ...
    def unload(self, full: bool = ...): ...
    def boot(self): ...
    def welcome(self): ...
    def load_logging(
        self, level: int | str = ..., format: str | None = ..., unique: bool = ...
    ): ...
    def unload_logging(self, safe: bool = ...): ...
    def flush_logging(self, raise_e: bool = ...): ...
    def extra_logging(self, level: int | str, formatter: Formatter): ...
    def level_logging(self, level: int | str): ...
    def load_diag(self, env: bool = ...): ...
    def unload_diag(self): ...
    def load_middleware(self, suffix: str = ...): ...
    def unload_middleware(self): ...
    def register_middleware(
        self, middleware_c: type[Middleware], *args, **kwargs
    ) -> Middleware: ...
    def call_middleware(self, name: str, *args, **kwargs): ...
    def bind_signals(
        self,
        signals: Sequence[int | None] = ...,
        handler: Callable[[int, FrameType | None], Any] | int | None = ...,
    ): ...
    def unbind_signals(self, signals: Sequence[int | None] = ...): ...
    def bind_config(self, signals: Sequence[int | None] = ...): ...
    def unbind_config(self, signals: Sequence[int | None] = ...): ...
    def bind_env(self): ...
    def forever(self, env: bool = ...): ...
    def start(self): ...
    def stop(self): ...
    def pause(self): ...
    def resume(self): ...
    def close(self): ...
    def finish(self): ...
    def main(self): ...
    def is_main(self) -> bool: ...
    def is_running(self) -> bool: ...
    def is_started(self) -> bool: ...
    def is_stopped(self) -> bool: ...
    def is_paused(self) -> bool: ...
    def is_edge(self) -> bool: ...
    def is_empty(self) -> bool: ...
    def is_sub_read(self, socket: socket | EventFile) -> bool: ...
    def is_sub_write(self, socket: socket | EventFile) -> bool: ...
    def is_sub_error(self, socket: socket | EventFile) -> bool: ...
    def sub_all(self, socket: socket | EventFile): ...
    def unsub_all(self, socket: socket | EventFile): ...
    def sub_read(self, socket: socket | EventFile): ...
    def sub_write(self, socket: socket | EventFile): ...
    def sub_error(self, socket: socket | EventFile): ...
    def unsub_read(self, socket: socket | EventFile): ...
    def unsub_write(self, socket: socket | EventFile): ...
    def unsub_error(self, socket: socket | EventFile): ...
    def cleanup(self, destroy: bool = ...): ...
    def loop(self): ...
    def block(self): ...
    def fork(self, timeout: float = ...) -> bool: ...
    def finalize(self): ...
    def ticks(self): ...
    def reads(self, reads: Sequence[socket | EventFile], state: bool = ...): ...
    def writes(self, writes: Sequence[socket | EventFile], state: bool = ...): ...
    def errors(self, errors: Sequence[socket | EventFile], state: bool = ...): ...
    def serve(
        self,
        host: str | None = ...,
        port: int | str = ...,
        type: int = ...,
        ipv6: bool = ...,
        ssl: bool = ...,
        key_file: str | None = ...,
        cer_file: str | None = ...,
        ca_file: str | None = ...,
        ca_root: bool = ...,
        ssl_verify: bool = ...,
        ssl_host: str | None = ...,
        ssl_fingerprint: str | None = ...,
        ssl_dump: bool = ...,
        family: int = ...,
        backlog: int = ...,
        env: bool = ...,
        callback: Callable[[Service, Callable[[], Any], bool], Any] | None = ...,
    ): ...
    def socket_tcp(
        self,
        ssl: bool = ...,
        key_file: str | None = ...,
        cer_file: str | None = ...,
        ca_file: str | None = ...,
        ca_root: bool = ...,
        ssl_verify: bool = ...,
        family: int = ...,
        type: int = ...,
        receive_buffer: int | None = ...,
        send_buffer: int | None = ...,
    ) -> socket: ...
    def socket_udp(self, family: int = ..., type: int = ...) -> socket: ...
    def datagram(
        self,
        family: int = ...,
        type: int = ...,
        local_host: str | None = ...,
        local_port: int | None = ...,
        remote_host: str | None = ...,
        remote_port: int | None = ...,
        callback: Callable[[Connection, bool], Any] | None = ...,
    ) -> Connection: ...
    def connect(
        self,
        host: str,
        port: int | str,
        receive_buffer: int | None = ...,
        send_buffer: int | None = ...,
        ssl: bool = ...,
        key_file: str | None = ...,
        cer_file: str | None = ...,
        ca_file: str | None = ...,
        ca_root: bool = ...,
        ssl_verify: bool = ...,
        family: int = ...,
        type: int = ...,
        callback: Callable[[Connection, bool], Any] | None = ...,
        env: bool = ...,
    ) -> Connection: ...
    def acquire(self, connection: Connection): ...
    def pregister(self, pool: EventPool): ...
    def punregister(self, pool: EventPool): ...
    def pcallback(self, event: str, socket: socket | EventFile, pool: EventPool): ...
    def nensure(self): ...
    def nstart(self): ...
    def nstop(self): ...
    def tensure(self): ...
    def tstart(self): ...
    def tstop(self): ...
    def texecute(
        self,
        callable: Callable[..., Any],
        args: Sequence[Any] = ...,
        kwargs: Mapping[str, Any] = ...,
        callback: Callable[..., Any] | None = ...,
    ): ...
    def files(self): ...
    def fopen(self, *args, **kwargs): ...
    def fclose(self, *args, **kwargs): ...
    def fread(self, *args, **kwargs): ...
    def fwrite(self, *args, **kwargs): ...
    def fensure(self): ...
    def fstart(self): ...
    def fstop(self): ...
    def on_connection_c(self, connection: Connection): ...
    def on_connection_d(self, connection: Connection): ...
    def on_stream_c(self, stream: Stream): ...
    def on_stream_d(self, stream: Stream): ...
    def on_fork(self): ...
    def on_join(self): ...
    def on_child(self, pipe: Callable[[str], Any] | None = ...): ...
    def on_command(self, command: str): ...
    def on_diag(self): ...
    def on_start(self): ...
    def on_stop(self): ...
    def on_pause(self): ...
    def on_resume(self): ...
    def on_config(self): ...
    def on_read(self, _socket: socket | EventFile): ...
    def on_write(self, _socket: socket | EventFile): ...
    def on_error(self, _socket: socket | EventFile): ...
    def on_read_s(self, _socket: socket, service: Service): ...
    def on_exception(self, exception: BaseException, connection: Connection): ...
    def on_exception_s(self, exception: BaseException): ...
    def on_expected(self, exception: BaseException, connection: Connection): ...
    def on_expected_s(self, exception: BaseException): ...
    def on_connect(self, connection: Connection): ...
    def on_upgrade(self, connection: Connection): ...
    def on_client_ssl(self, connection: Connection): ...
    def on_acquire(self, connection: Connection): ...
    def on_acquire_base(self, connection: Connection): ...
    def on_release(self, connection: Connection): ...
    def on_release_base(self, connection: Connection): ...
    def on_data(self, connection: Connection, data: bytes): ...
    def on_data_base(self, connection: Connection, data: bytes): ...
    def on_serve(self): ...
    def info_dict(self, full: bool = ...) -> dict[str, Any]: ...
    def log_dict(self, full: bool = ...) -> dict[str, Any]: ...
    def info_string(self, full: bool = ..., safe: bool = ...) -> str: ...
    def record_closed(self, connection: Connection): ...
    def connections_dict(self, full: bool = ...) -> list[dict[str, Any]]: ...
    def connection_dict(self, id: str, full: bool = ...) -> dict[str, Any] | None: ...
    def connections_closed_dict(self) -> list[dict[str, Any]]: ...
    def build_connection(
        self,
        socket: socket,
        address: tuple[str, int] | str | None = ...,
        datagram: bool = ...,
        ssl: bool = ...,
    ) -> Connection: ...
    def build_connection_client(
        self,
        socket_c: socket,
        address: tuple[str, int] | str,
        ssl: bool = ...,
        receive_buffer_c: int | None = ...,
        send_buffer_c: int | None = ...,
    ) -> Connection | None: ...
    def base_connection(self, *args, **kwargs) -> Connection: ...
    def new_connection(self, connection: Connection): ...
    def del_connection(self, connection: Connection): ...
    def new_service(
        self,
        socket: socket,
        host: str | None = ...,
        port: int | str | None = ...,
        ssl: bool = ...,
    ) -> Service: ...
    def add_callback(
        self,
        socket: socket | EventFile,
        callback: Callable[[str, socket | EventFile], Any],
    ): ...
    def remove_callback(
        self,
        socket: socket | EventFile,
        callback: Callable[[str, socket | EventFile], Any],
    ): ...
    def load_config(self, path: str = ..., **kwargs): ...
    def apply_config(
        self, path: str, kwargs: Mapping[str, Any]
    ) -> Mapping[str, Any]: ...
    def exec_safe(
        self, connection: Connection, callable: Callable[..., Any], *args, **kwargs
    ) -> Any: ...
    def is_devel(self) -> bool: ...
    def is_trace(self) -> bool: ...
    def is_debug(self) -> bool: ...
    def is_info(self) -> bool: ...
    def is_warning(self) -> bool: ...
    def is_error(self) -> bool: ...
    def is_critical(self) -> bool: ...
    def trace(self, object: Any, *args, **kwargs): ...
    def debug(self, object: Any, *args, **kwargs): ...
    def info(self, object: Any, *args, **kwargs): ...
    def warning(self, object: Any, *args, **kwargs): ...
    def error(self, object: Any, *args, **kwargs): ...
    def critical(self, object: Any, *args, **kwargs): ...
    def log_stack(self, method: Callable[..., Any] | None = ..., info: bool = ...): ...
    def log_info(self, method: Callable[..., Any] | None = ...): ...
    def log(self, *args, **kwargs): ...
    def log_python_3(self, object: Any, *args, **kwargs): ...
    def log_python_2(self, object: Any, *args, **kwargs): ...
    def log_ctx(self) -> dict[str, Any]: ...
    def log_stack_ctx(self) -> dict[str, list[str]]: ...
    def add_log_extra(self, kwargs: dict[str, Any], key: str, value: Any): ...
    def add_log_ctx(
        self, kwargs: dict[str, Any], callable: Callable[[], Mapping[str, Any]]
    ): ...
    def add_log_stack(self, kwargs: dict[str, Any]): ...
    def build_poll(self) -> Poll: ...
    def build_future(self, compat: bool = ..., asyncio: bool = ...) -> Future: ...
    def get_id(self, unique: bool = ...) -> str: ...
    def get_poll(self) -> Poll: ...
    def get_poll_name(self) -> str: ...
    def get_state(self) -> int: ...
    def set_state(self, state: int): ...
    def get_state_s(self, lower: bool = ...) -> str: ...
    def get_env(
        self,
        name: str,
        default: Any = ...,
        cast: type | None = ...,
        expand: bool = ...,
    ) -> Any: ...
    def expand(
        self, value: str | bytes | None, encoding: str = ..., force: bool = ...
    ) -> str | bytes | None: ...
    def get_protocols(self) -> list[str] | None: ...
    def get_adapter(self, name: str = ..., *args, **kwargs) -> BaseAdapter: ...
    def get_auth(self, name: str = ..., *args, **kwargs) -> type[Auth]: ...
    def get_connection(self, socket: socket) -> Connection: ...
    @property
    def is_parent(self) -> bool: ...
    @property
    def is_child(self) -> bool: ...
    @property
    def is_forked(self) -> bool: ...
    def _pending(self, connection: Connection) -> bool: ...
    def _notifies(self) -> int: ...
    def _delays(self): ...
    def _generate(self, hashed: bool = ...) -> str: ...
    def _connect(self, connection: Connection): ...
    def _connectf(self, connection: Connection): ...
    def _socket_keepalive(
        self,
        _socket: socket,
        timeout: int | None = ...,
        interval: int | None = ...,
        count: int | None = ...,
    ): ...
    def _socket_option(
        self, _socket: socket, level: int, option: int | None, value: int
    ) -> bool: ...
    def _ssl_init(self, strict: bool = ..., env: bool = ...): ...
    def _ssl_destroy(self): ...
    def _ssl_reload(self): ...
    def _ssl_callback(
        self, socket: SSLSocket | SSLObject, hostname: str | None, context: SSLContext
    ): ...
    def _ssl_ctx(
        self,
        values: Mapping[str, Any],
        context: SSLContext | None = ...,
        secure: int = ...,
        context_options: Sequence[str] = ...,
    ) -> SSLContext: ...
    def _ssl_ctx_base(
        self,
        context: SSLContext,
        secure: int = ...,
        context_options: Sequence[str] = ...,
    ): ...
    def _ssl_ctx_protocols(self, context: SSLContext): ...
    def _ssl_ctx_alpn(self, context: SSLContext): ...
    def _ssl_ctx_npn(self, context: SSLContext): ...
    def _ssl_ctx_debug(
        self,
        context: SSLContext,
        secure: int = ...,
        context_options: Sequence[str] = ...,
    ): ...
    def _ssl_certs(
        self,
        context: SSLContext,
        key_file: str | None = ...,
        cer_file: str | None = ...,
        ca_file: str | None = ...,
        ca_root: bool = ...,
        verify_mode: VerifyMode = ...,
        check_hostname: bool = ...,
    ): ...
    def _ssl_upgrade(
        self,
        _socket: socket,
        key_file: str | None = ...,
        cer_file: str | None = ...,
        ca_file: str | None = ...,
        ca_root: bool = ...,
        server: bool = ...,
        ssl_verify: bool = ...,
        server_hostname: str | None = ...,
    ) -> SSLSocket: ...
    def _ssl_wrap(
        self,
        _socket: socket,
        key_file: str | None = ...,
        cer_file: str | None = ...,
        ca_file: str | None = ...,
        ca_root: bool = ...,
        server: bool = ...,
        ssl_verify: bool = ...,
        server_hostname: str | None = ...,
    ) -> SSLSocket: ...
    def _ssl_handshake(self, connection: Connection): ...
    def _ssl_client_handshake(self, connection: Connection): ...
    def _ssl_reason(self, error: SSLError) -> str | None: ...
    def _expand_destroy(self): ...
    def _level(self, level: int | str | None) -> int | str | None: ...
    def _format_delta(self, time_delta: timedelta, count: int = ...) -> str: ...
    def _wait_forever(self, sleep: float = ...): ...

class DiagBase(AbstractBase):
    reads_c: int
    writes_c: int
    errors_c: int

    def __init__(self, *args, **kwargs): ...
    def reads(self, *args, **kwargs): ...
    def writes(self, *args, **kwargs): ...
    def errors(self, *args, **kwargs): ...
    def info_dict(self, full: bool = ...) -> dict[str, Any]: ...

class BaseThread(Thread):
    owner: AbstractBase | None
    daemon: bool

    def __init__(
        self, owner: AbstractBase | None = ..., daemon: bool = ..., *args, **kwargs
    ): ...
    def run(self): ...

def new_loop_main(
    factory: type[AbstractBase] | None = ...,
    env: bool = ...,
    _compat: bool | None = ...,
    **kwargs
) -> AbstractBase | CompatLoop: ...
def new_loop_asyncio(**kwargs) -> AbstractEventLoop | None: ...
def new_loop(
    factory: type[AbstractBase] | None = ...,
    _compat: bool | None = ...,
    asyncio: bool | None = ...,
    **kwargs
) -> AbstractBase | CompatLoop | AbstractEventLoop | None: ...
def ensure_main(
    factory: type[AbstractBase] | None = ..., env: bool = ..., **kwargs
): ...
def ensure_asyncio(**kwargs) -> AbstractEventLoop | None: ...
def ensure_loop(
    factory: type[AbstractBase] | None = ..., asyncio: bool | None = ..., **kwargs
): ...
def get_main(
    factory: type[AbstractBase] | None = ..., ensure: bool = ..., **kwargs
) -> AbstractBase | None: ...
def get_loop(
    factory: type[AbstractBase] | None = ...,
    ensure: bool = ...,
    _compat: bool | None = ...,
    asyncio: bool | None = ...,
    **kwargs
) -> AbstractBase | CompatLoop | AbstractEventLoop | None: ...
def get_event_loop(
    *args, **kwargs
) -> AbstractBase | CompatLoop | AbstractEventLoop | None: ...
def stop_loop(compat: bool = ..., asyncio: bool = ...): ...
def compat_loop(loop: AbstractBase | CompatLoop | None) -> CompatLoop | None: ...
def get_poll() -> Poll | None: ...
def build_future(compat: bool = ..., asyncio: bool = ...) -> Future | None: ...
def ensure(
    coroutine: Any,
    args: Sequence[Any] = ...,
    kwargs: Mapping[str, Any] = ...,
    thread: bool | None = ...,
) -> Future: ...
def ensure_pool(
    coroutine: Any, args: Sequence[Any] = ..., kwargs: Mapping[str, Any] = ...
) -> Future: ...

is_diag: bool
Base = AbstractBase
