from contextlib import contextmanager
from typing import Any, Callable, Iterator, Mapping, Sequence

FILE_NAME: str
FILE_TEMPLATE: str
HOME_FILE: str
IMPORT_NAMES: tuple[str, ...]
CASTS: dict[type, Callable[[Any], Any]]
ENV_ENCODINGS: tuple[str, ...]
CONFIGS: dict[str, Any]
CONFIG_F: list[str]
HOMES: list[str]

def conf(
    name: str,
    default: Any = ...,
    cast: Callable[[Any], Any] | str | None = ...,
    ctx: Mapping[str, Any] | None = ...,
) -> Any: ...
def conf_prefix(prefix: str, ctx: Mapping[str, Any] | None = ...) -> dict[str, Any]: ...
def conf_suffix(suffix: str, ctx: Mapping[str, Any] | None = ...) -> dict[str, Any]: ...
def conf_s(name: str, value: Any, ctx: Mapping[str, Any] | None = ...): ...
def conf_r(name: str, ctx: Mapping[str, Any] | None = ...): ...
def conf_d(ctx: Mapping[str, Any] | None = ...) -> dict[str, Any]: ...
def conf_ctx() -> dict[str, dict[str, Any]]: ...
@contextmanager
def conf_override(name: str, value: Any) -> Iterator[None]: ...
def load(
    names: Sequence[str] = ...,
    path: str | None = ...,
    encoding: str = ...,
    ctx: Mapping[str, Any] | None = ...,
): ...
def load_file(
    name: str = ...,
    path: str | None = ...,
    encoding: str = ...,
    ctx: Mapping[str, Any] | None = ...,
): ...
def load_dot_env(
    name: str = ..., encoding: str = ..., ctx: Mapping[str, Any] | None = ...
): ...
def load_env(ctx: Mapping[str, Any] | None = ...): ...
def get_homes(
    file_path: str = ...,
    default: str = ...,
    encoding: str = ...,
    force_default: bool = ...,
) -> list[str]: ...
def _cast_r(cast: Callable[[Any], Any] | str | None) -> Callable[[Any], Any] | None: ...
def _load_includes(base_path: str, config: Mapping[str, Any], encoding: str = ...): ...
def _is_valid(key: str) -> bool: ...
def _is_devel() -> bool: ...
def _is_secure() -> bool: ...
