from collections import deque
from os import PathLike
from socket import socket as _socket
from threading import RLock
from typing import Any, Callable

from netius import Base, Observable

OPEN: int
CLOSED: int
PENDING: int
CHUNK_SIZE: int
REASON_TIMEOUT: str
REASON_CLIENT_EOF: str
REASON_UPSTREAM_ERROR: str
REASON_ERROR: str
REASON_EXPLICIT: str
REASON_UNKNOWN: str

class BaseConnection(Observable):
    status: int
    id: str
    connecting: bool
    upgrading: bool
    owner: Base | None
    socket: _socket | None
    address: tuple[Any, ...] | None
    datagram: bool
    ssl: bool
    ssl_host: str | None
    ssl_fingerprint: str | None
    ssl_handshake: bool
    ssl_connecting: bool
    ssl_dump: bool
    max_pending: int
    min_pending: int
    renable: bool
    wready: bool
    pending_s: int
    restored_s: int
    close_reason: str | None
    close_error: str | None
    close_timestamp: float | None
    starters: deque[Callable[[BaseConnection], Any]]
    pending: deque[
        tuple[
            bytes | None,
            tuple[Any, ...] | None,
            Callable[[BaseConnection], Any] | None,
        ]
    ]
    restored: deque[bytes]
    pending_lock: RLock
    restored_lock: RLock

    def __init__(
        self,
        owner: Base | None = ...,
        socket: _socket | None = ...,
        address: tuple[Any, ...] | None = ...,
        datagram: bool = ...,
        ssl: bool = ...,
        max_pending: int = ...,
        min_pending: int = ...,
    ): ...
    def destroy(self): ...
    def open(self, connect: bool = ...): ...
    def close(
        self,
        flush: bool = ...,
        destroy: bool = ...,
        reason: str | None = ...,
        error: str | None = ...,
    ): ...
    def close_flush(self): ...
    def upgrade(
        self,
        key_file: PathLike[str] | None = ...,
        cer_file: PathLike[str] | None = ...,
        ca_file: PathLike[str] | None = ...,
        server: bool = ...,
    ): ...
    def set_connecting(self): ...
    def set_connected(self): ...
    def set_upgraded(self): ...
    def set_data(self, data: bytes, address: tuple[Any, ...] | None = ...): ...
    def set_exception(self, exception: BaseException): ...
    def ensure_write(self, flush: bool = ...) -> Any: ...
    def remove_write(self): ...
    def enable_read(self): ...
    def disable_read(self): ...
    def send(
        self,
        data: bytes | str | None,
        address: tuple[Any, ...] | None = ...,
        delay: bool = ...,
        force: bool = ...,
        callback: Callable[[BaseConnection], Any] | None = ...,
    ) -> int: ...
    def recv(self, size: int = ..., force: bool = ...) -> bytes | tuple[bytes, Any]: ...
    def pend(
        self,
        data: (
            bytes
            | tuple[
                bytes | None,
                tuple[Any, ...] | None,
                Callable[[BaseConnection], Any] | None,
            ]
        ),
        back: bool = ...,
    ): ...
    def restore(self, data: bytes, back: bool = ...): ...
    def run_starter(self) -> bool: ...
    def end_starter(self): ...
    def add_starter(
        self, starter: Callable[[BaseConnection], Any], back: bool = ...
    ): ...
    def remove_starter(self, starter: Callable[[BaseConnection], Any]): ...
    def info_dict(self, full: bool = ...) -> dict[str, Any]: ...
    def log_dict(self, full: bool = ...) -> dict[str, Any]: ...
    def ssl_certificate(self, binary: bool = ...) -> dict[str, Any] | bytes | None: ...
    def ssl_verify_host(self, host: str | None = ...): ...
    def ssl_verify_fingerprint(self, fingerprint: str | None = ...): ...
    def ssl_dump_certificate(self, dump: bool = ...): ...
    def ssl_protocol(self) -> str | None: ...
    def ssl_alpn_protocol(self) -> str | None: ...
    def ssl_npn_protocol(self) -> str | None: ...
    def trace(self, object: Any, *args, **kwargs): ...
    def debug(self, object: Any, *args, **kwargs): ...
    def info(self, object: Any, *args, **kwargs): ...
    def warning(self, object: Any, *args, **kwargs): ...
    def error(self, object: Any, *args, **kwargs): ...
    def critical(self, object: Any, *args, **kwargs): ...
    def log_ctx(self) -> dict[str, Any]: ...
    def is_open(self) -> bool: ...
    def is_closed(self) -> bool: ...
    def is_pending(self) -> bool: ...
    def is_connected(self) -> bool: ...
    def is_connecting(self) -> bool: ...
    def is_upgrading(self) -> bool: ...
    def is_throttleable(self) -> bool: ...
    def is_exhausted(self) -> bool: ...
    def is_restored(self) -> bool: ...
    def is_pending_data(self) -> bool: ...
    def _send(self): ...
    def _recv(self, size: int) -> bytes | tuple[bytes, Any]: ...
    def _recv_ssl(self, size: int) -> bytes: ...
    def _recv_restored(self, size: int) -> bytes: ...
    def _shutdown(self, close: bool = ..., force: bool = ..., ignore: bool = ...): ...
    def _close_callback(self, connection: BaseConnection): ...
    def _flush_write(self): ...
    def _safe_socket_attr(self, name: str) -> Any: ...
    @property
    def _has_starter(self) -> bool: ...
    @property
    def _safe_address(self) -> tuple[Any, ...] | None: ...
    @property
    def _safe_fileno(self) -> int | None: ...

class DiagConnection(BaseConnection):
    creation: float
    recvs: int
    sends: int
    in_bytes: int
    out_bytes: int
    last_recv_ts: float | None
    last_send_ts: float | None

    def __init__(self, *args, **kwargs): ...
    def recv(self, *args, **kwargs) -> bytes | tuple[bytes, Any]: ...
    def send(self, data: bytes | str | None, *args, **kwargs) -> int: ...
    def info_dict(self, full: bool = ...) -> dict[str, Any]: ...
    def _last_activity(self) -> float | None: ...
    def _uptime(self) -> str: ...
    def _resolve(self, address: tuple[Any, ...] | None) -> dict[str, Any] | None: ...

is_diag: bool
Connection = BaseConnection
