from typing import Any

from netius import Agent, StreamServer
from netius.base.common import *

class Container(Base):
    owner: Base | None
    bases: list[Base | Agent]

    def __init__(self, *args, **kwargs): ...
    def start(self, owner: Base): ...  # type: ignore[override]
    def cleanup(self): ...
    def loop(self): ...
    def ticks(self): ...
    def connections_dict(  # type: ignore[override]
        self, full: bool = ...
    ) -> dict[str, Any]: ...
    def connection_dict(self, id: str, full: bool = ...) -> dict[str, Any] | None: ...
    def on_start(self): ...
    def on_stop(self): ...
    def add_base(self, base: Base | Agent): ...
    def remove_base(self, base: Base | Agent): ...
    def start_base(self, base: Base | Agent): ...
    def start_all(self): ...
    def apply_all(self): ...
    def apply_base(self, base: Base | Agent): ...
    def call_all(self, name: str, *args, **kwargs): ...
    def trigger_all(self, name: str, *args, **kwargs): ...

class ContainerServer(StreamServer):
    container: Container | None

    def __init__(self, *args, **kwargs): ...
    def start(self): ...
    def stop(self): ...
    def cleanup(self): ...
    def add_base(self, base: Base | Agent): ...
