from uuid import UUID
from typing import Any

class NetiusError(Exception):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_kwarg(self, name: str, default: Any | None = ...): ...
    @property
    def uid(self) -> UUID: ...

class RuntimeError(NetiusError): ...
class StopError(RuntimeError): ...
class PauseError(RuntimeError): ...
class WakeupError(RuntimeError): ...
class DataError(RuntimeError): ...

class ParserError(RuntimeError):
    def __init__(self, *args, **kwargs) -> None: ...

class GeneratorError(RuntimeError): ...
class SecurityError(RuntimeError): ...
class NotImplemented(RuntimeError): ...
class AssertionError(RuntimeError): ...
