from builtins import bytes as _bytes, range as _range, str as _str
from contextlib import contextmanager
from datetime import datetime
from http.client import (
    HTTPConnection as _HTTPConnection,
    HTTPSConnection as _HTTPSConnection,
)
from io import BytesIO as _BytesIO, StringIO as _StringIO
from types import ModuleType
from typing import (
    Any,
    Callable,
    ItemsView,
    Iterable,
    Iterator,
    KeysView,
    Mapping,
    NamedTuple,
    ValuesView,
)
from urllib.error import HTTPError as _HTTPError
from urllib.parse import ParseResult
from urllib.request import (
    HTTPHandler as _HTTPHandler,
    OpenerDirector,
    Request as _Request,
)

class ArgSpec(NamedTuple):
    args: list[_str]
    varargs: _str | None
    keywords: _str | None
    defaults: tuple[Any, ...] | None

@contextmanager
def ctx_absolute() -> Iterator[None]: ...

PYTHON_3: bool
PYTHON_33: bool
PYTHON_35: bool
PYTHON_36: bool
PYTHON_39: bool
PYTHON_ASYNC: bool
PYTHON_ASYNC_GEN: bool
PYTHON_V: int
LONG: type[int]
BYTES: type[_bytes]
UNICODE: type[_str]
OLD_UNICODE: None
STRINGS: tuple[type, ...]
ALL_STRINGS: tuple[type, ...]
INTEGERS: tuple[type, ...]
Request: type[_Request]
HTTPHandler: type[_HTTPHandler]
HTTPError: type[_HTTPError]
HTTPConnection: type[_HTTPConnection]
HTTPSConnection: type[_HTTPSConnection]

def with_meta(meta: type, *bases) -> type: ...
def eager(iterable: Iterable[Any]) -> list[Any]: ...
def iteritems(associative: Mapping[Any, Any]) -> ItemsView[Any, Any]: ...
def iterkeys(associative: Mapping[Any, Any]) -> KeysView[Any]: ...
def itervalues(associative: Mapping[Any, Any]) -> ValuesView[Any]: ...
def items(associative: Mapping[Any, Any]) -> list[tuple[Any, Any]]: ...
def keys(associative: Mapping[Any, Any]) -> list[Any]: ...
def values(associative: Mapping[Any, Any]) -> list[Any]: ...
def xrange(start: int, stop: int | None = ..., step: int = ...) -> _range: ...
def range(start: int, stop: int | None = ..., step: int = ...) -> list[int]: ...
def ord(value: int | _str | _bytes) -> int: ...
def chr(value: int) -> _bytes: ...
def chri(value: int) -> int: ...
def bytes(
    value: _str | _bytes | None,
    encoding: _str = ...,
    errors: _str = ...,
    force: bool = ...,
) -> _bytes | None: ...
def str(
    value: _str | _bytes | None,
    encoding: _str = ...,
    errors: _str = ...,
    force: bool = ...,
) -> _str | None: ...
def u(
    value: Any, encoding: _str = ..., errors: _str = ..., force: bool = ...
) -> Any: ...
def ascii(value: Any, encoding: _str = ..., errors: _str = ...) -> _str: ...
def orderable(value: Iterable[Any]) -> Orderable: ...
def is_str(value: Any) -> bool: ...
def is_unicode(value: Any) -> bool: ...
def is_bytes(value: Any) -> bool: ...
def is_string(value: Any, all: bool = ...) -> bool: ...
def is_generator(value: Any) -> bool: ...
def is_async_generator(value: Any) -> bool: ...
def is_unittest(name: _str = ...) -> bool: ...
def execfile(
    path: _str,
    global_vars: dict[_str, Any],
    local_vars: dict[_str, Any] | None = ...,
    encoding: _str = ...,
): ...
def walk(path: _str, visit: Callable[[Any, _str, list[_str]], Any], arg: Any): ...
def getargspec(func: Callable[..., Any]) -> ArgSpec: ...
def has_module(name: _str) -> bool: ...
def new_module(name: _str) -> ModuleType: ...
def reduce(*args, **kwargs) -> Any: ...
def reload(*args, **kwargs) -> ModuleType: ...
def unichr(*args, **kwargs) -> _str: ...
def urlopen(*args, **kwargs) -> Any: ...
def build_opener(*args, **kwargs) -> OpenerDirector: ...
def to_timestamp(date_time: datetime) -> float: ...
def to_datetime(timestamp: float) -> datetime: ...
def utcfromtimestamp(timestamp: float) -> datetime: ...
def utc_now() -> datetime: ...
def urlparse(*args, **kwargs) -> ParseResult: ...
def urlunparse(*args, **kwargs) -> _str: ...
def parse_qs(*args, **kwargs) -> dict[_str, list[_str]]: ...
def urlencode(*args, **kwargs) -> _str: ...
def quote(*args, **kwargs) -> _str: ...
def quote_plus(*args, **kwargs) -> _str: ...
def unquote(*args, **kwargs) -> _str: ...
def unquote_plus(*args, **kwargs) -> _str: ...
def cmp_to_key(*args, **kwargs) -> dict[_str, Any]: ...
def tobytes(self: Any, *args, **kwargs) -> _bytes: ...
def tostring(self: Any, *args, **kwargs) -> _bytes: ...
def StringIO(*args, **kwargs) -> _StringIO: ...
def BytesIO(*args, **kwargs) -> _BytesIO: ...

class Orderable(tuple):
    def __cmp__(self, value: Any) -> Any: ...
    def __lt__(self, value: Any) -> bool: ...
