from socket import socket as _socket
from typing import Any

class ConnectionCompat:
    @property
    def id(self) -> str | None: ...
    @property
    def socket(self) -> _socket | None: ...
    @property
    def address(self) -> Any: ...
    @address.setter
    def address(self, value: Any): ...
    @property
    def status(self) -> int | None: ...
    @status.setter
    def status(self, value: int): ...
    @property
    def renable(self) -> bool: ...
    @renable.setter
    def renable(self, value: bool): ...
    def is_throttleable(self) -> bool: ...
    def is_exhausted(self) -> bool: ...
    def is_restored(self) -> bool: ...
    def disable_read(self): ...
    def enable_read(self): ...
    @property
    def max_pending(self) -> int: ...
    @max_pending.setter
    def max_pending(self, value: int): ...
    @property
    def min_pending(self) -> int: ...
    @min_pending.setter
    def min_pending(self, value: int): ...
    @property
    def waiting(self) -> bool: ...
    @waiting.setter
    def waiting(self, value: bool): ...
    @property
    def busy(self) -> int: ...
    @busy.setter
    def busy(self, value: int): ...
    @property
    def state(self) -> Any: ...
    @state.setter
    def state(self, value: Any): ...
    @property
    def error_url(self) -> str | None: ...
    @error_url.setter
    def error_url(self, value: str | None): ...
