class Observable:
    def __init__(self, *args, **kwargs) -> None: ...
    def build(self) -> None: ...
    def destroy(self) -> None: ...
    def bind(self, name: str, method: str, oneshot: bool = ...) -> None: ...
    def unbind(self, name: str, method: str | None = ...) -> None: ...
    def unbind_all(self) -> None: ...
    def trigger(self, name: str, *args, **kwargs) -> None: ...
