from typing import Any, Callable

class Observable:
    events: dict[str, list[Callable[..., Any]]]

    def __init__(self, *args, **kwargs): ...
    def build(self): ...
    def destroy(self): ...
    def bind(self, name: str, method: Callable[..., Any], oneshot: bool = ...): ...
    def unbind(self, name: str, method: Callable[..., Any] | None = ...): ...
    def unbind_all(self): ...
    def trigger(self, name: str, *args, **kwargs): ...
