from socket import socket

from netius import Base

POLL_TIMEOUT: float

class Poll:
    timeout: float | None
    read_o: dict[socket, Base | None]
    write_o: dict[socket, Base | None]
    error_o: dict[socket, Base | None]

    def __init__(self): ...
    @classmethod
    def name(cls) -> str: ...
    @classmethod
    def test(cls) -> bool: ...
    def open(self, timeout: float = ...): ...
    def close(self): ...
    def poll(self) -> tuple[list[socket], list[socket], list[socket]]: ...
    def poll_owner(
        self,
    ) -> dict[Base | None, tuple[list[socket], list[socket], list[socket]]]: ...
    def is_open(self) -> bool: ...
    def is_edge(self) -> bool: ...
    def is_empty(self) -> bool: ...
    def sub_all(self, socket: socket, owner: Base | None = ...): ...
    def unsub_all(self, socket: socket): ...
    def is_sub_read(self, socket: socket) -> bool: ...
    def is_sub_write(self, socket: socket) -> bool: ...
    def is_sub_error(self, socket: socket) -> bool: ...
    def sub_read(self, socket: socket, owner: Base | None = ...): ...
    def sub_write(self, socket: socket, owner: Base | None = ...): ...
    def sub_error(self, socket: socket, owner: Base | None = ...): ...
    def unsub_read(self, socket: socket): ...
    def unsub_write(self, socket: socket): ...
    def unsub_error(self, socket: socket): ...

class EpollPoll(Poll):
    def __init__(self, *args, **kwargs): ...
    @classmethod
    def test(cls) -> bool: ...
    def open(self, timeout: float = ...): ...
    def close(self): ...
    def poll(self) -> tuple[list[socket], list[socket], list[socket]]: ...
    def is_edge(self) -> bool: ...
    def unsub_all(self, socket: socket): ...
    def sub_read(self, socket: socket, owner: Base | None = ...): ...
    def sub_write(self, socket: socket, owner: Base | None = ...): ...
    def sub_error(self, socket: socket, owner: Base | None = ...): ...
    def unsub_read(self, socket: socket): ...
    def unsub_write(self, socket: socket): ...
    def unsub_error(self, socket: socket): ...

class KqueuePoll(Poll):
    def __init__(self, *args, **kwargs): ...
    @classmethod
    def test(cls) -> bool: ...
    def open(self, timeout: float = ...): ...
    def close(self): ...
    def poll(self) -> tuple[list[socket], list[socket], list[socket]]: ...
    def is_edge(self) -> bool: ...
    def unsub_all(self, socket: socket): ...
    def sub_read(self, socket: socket, owner: Base | None = ...): ...
    def sub_write(self, socket: socket, owner: Base | None = ...): ...
    def sub_error(self, socket: socket, owner: Base | None = ...): ...
    def unsub_read(self, socket: socket): ...
    def unsub_write(self, socket: socket): ...
    def unsub_error(self, socket: socket): ...

class PollPoll(Poll):
    def __init__(self, *args, **kwargs): ...
    @classmethod
    def test(cls) -> bool: ...
    def open(self, timeout: float = ...): ...
    def close(self): ...
    def poll(self) -> tuple[list[socket], list[socket], list[socket]]: ...
    def is_edge(self) -> bool: ...
    def sub_read(self, socket: socket, owner: Base | None = ...): ...
    def sub_write(self, socket: socket, owner: Base | None = ...): ...
    def sub_error(self, socket: socket, owner: Base | None = ...): ...
    def unsub_read(self, socket: socket): ...
    def unsub_write(self, socket: socket): ...
    def unsub_error(self, socket: socket): ...

class SelectPoll(Poll):
    def __init__(self, *args, **kwargs): ...
    def open(self, timeout: float = ...): ...
    def close(self): ...
    def poll(self) -> tuple[list[socket], list[socket], list[socket]]: ...
    def is_edge(self) -> bool: ...
    def sub_read(self, socket: socket, owner: Base | None = ...): ...
    def sub_write(self, socket: socket, owner: Base | None = ...): ...
    def sub_error(self, socket: socket, owner: Base | None = ...): ...
    def unsub_read(self, socket: socket): ...
    def unsub_write(self, socket: socket): ...
    def unsub_error(self, socket: socket): ...
