from asyncio import BaseTransport
from logging import Logger
from typing import Any, Callable

from netius import (
    Connection,
    ConnectionCompat,
    Observable,
    Request,
    Response,
    Transport,
)

logger: Logger

class Protocol(Observable):
    owner: Any

    def __init__(self, owner: Any = ...): ...
    def open(self): ...
    def close(self): ...
    def finish(self): ...
    def open_c(self): ...
    def close_c(self): ...
    def finish_c(self): ...
    def info_dict(self, full: bool = ...) -> dict[str, Any]: ...
    def connection_made(self, transport: Transport | BaseTransport): ...
    def connection_lost(self, exception: Exception | None): ...
    def transport(self) -> Transport | BaseTransport | None: ...
    def loop(self) -> Any: ...
    def loop_set(self, loop: Any): ...
    def loop_unset(self): ...
    def pause_writing(self): ...
    def resume_writing(self): ...
    def delay(
        self, callable: Callable[[], Any], timeout: float | None = ...
    ) -> Any: ...
    def unpend(self, callable_t: Any): ...
    def trace(self, object: Any, *args, **kwargs): ...
    def debug(self, object: Any, *args, **kwargs): ...
    def info(self, object: Any, *args, **kwargs): ...
    def warning(self, object: Any, *args, **kwargs): ...
    def error(self, object: Any, *args, **kwargs): ...
    def critical(self, object: Any, *args, **kwargs): ...
    def traced(self, message: str | None = ..., *args): ...
    def is_pending(self) -> bool: ...
    def is_open(self) -> bool: ...
    def is_closed(self) -> bool: ...
    def is_closing(self) -> bool: ...
    def is_closed_or_closing(self) -> bool: ...
    def is_devel(self) -> bool: ...
    def is_trace(self) -> bool: ...
    def _close_transport(self, force: bool = ...): ...
    def _delay_send(
        self,
        data: bytes,
        address: tuple[str, int] | None = ...,
        callback: Callable[..., Any] | None = ...,
    ) -> int: ...
    def _flush_callbacks(self): ...
    def _flush_send(self): ...
    def _log_fallback(self, level: int, object: Any, *args, **kwargs): ...

class DatagramProtocol(Protocol):
    requests: list[Request]
    requests_m: dict[int, Request]

    def __init__(self): ...
    def datagram_received(self, data: bytes, address: tuple[str, int]): ...
    def error_received(self, exception: Exception): ...
    def on_data(self, address: tuple[str, int], data: bytes): ...
    def send(
        self,
        data: bytes | str,
        address: tuple[str, int],
        delay: bool = ...,
        force: bool = ...,
        callback: Callable[..., Any] | None = ...,
    ) -> int: ...
    def send_to(
        self,
        data: bytes | str,
        address: tuple[str, int],
        delay: bool = ...,
        force: bool = ...,
        callback: Callable[..., Any] | None = ...,
    ) -> int: ...
    def add_request(self, request: Request): ...
    def remove_request(self, request: Request): ...
    def get_request(self, id: int | Response) -> Request | None: ...

class StreamProtocol(Protocol, ConnectionCompat):
    def connection_made(self, transport: Transport | BaseTransport): ...
    def data_received(self, data: bytes): ...
    def eof_received(self): ...
    def on_data(self, data: bytes): ...
    def send(
        self,
        data: bytes | str,
        delay: bool = ...,
        force: bool = ...,
        callback: Callable[..., Any] | None = ...,
    ) -> int: ...
    @property
    def connection(self) -> Connection | None: ...
