from collections import deque
from socket import socket as Socket
from threading import RLock
from typing import Any, Callable, Sequence

from netius import Connection
from netius.base.common import AbstractBase
from netius.base.common import *
from netius.base.conn import *
from netius.pool import EventFile

BUFFER_SIZE_S: int | None  # type: ignore[no-redef]
BUFFER_SIZE_C: int | None  # type: ignore[no-redef]

class Server(AbstractBase):
    receive_buffer_s: int | None
    send_buffer_s: int | None
    receive_buffer_c: int | None
    send_buffer_c: int | None
    socket: Socket | None
    host: str | None
    port: int | str | None
    type: int | None
    ssl: bool
    key_file: str | None
    cer_file: str | None
    ca_file: str | None
    env: bool
    allowed: list[str]

    def __init__(self, *args, **kwargs): ...
    def welcome(self): ...
    def cleanup(self): ...
    def info_dict(self, full: bool = ...) -> dict[str, Any]: ...
    def serve(  # type: ignore[override]
        self,
        host: str | None = ...,
        port: int | str = ...,
        type: int = ...,
        ipv6: bool = ...,
        ssl: bool = ...,
        key_file: str | None = ...,
        cer_file: str | None = ...,
        ca_file: str | None = ...,
        ca_root: bool = ...,
        ssl_verify: bool = ...,
        ssl_host: str | None = ...,
        ssl_fingerprint: str | None = ...,
        ssl_dump: bool = ...,
        setuid: int | None = ...,
        backlog: int = ...,
        load: bool = ...,
        start: bool = ...,
        env: bool = ...,
    ): ...
    def socket_tcp(  # type: ignore[override]
        self,
        ssl: bool = ...,
        key_file: str | None = ...,
        cer_file: str | None = ...,
        ca_file: str | None = ...,
        ca_root: bool = ...,
        ssl_verify: bool = ...,
        family: int = ...,
        type: int = ...,
    ) -> Socket: ...
    def socket_udp(self, family: int = ..., type: int = ...) -> Socket: ...
    def on_serve(self): ...

class DatagramServer(Server):
    renable: bool
    wready: bool
    pending_s: int
    pending: deque[tuple[Any, Any]]
    pending_lock: RLock

    def __init__(self, *args, **kwargs): ...
    def reads(self, reads: Sequence[Socket | EventFile], state: bool = ...): ...
    def writes(self, writes: Sequence[Socket | EventFile], state: bool = ...): ...
    def errors(self, errors: Sequence[Socket | EventFile], state: bool = ...): ...
    def serve(self, type: int = ..., *args, **kwargs): ...  # type: ignore[override]
    def on_read(self, _socket: Socket | EventFile): ...
    def on_write(self, _socket: Socket | EventFile): ...
    def on_error(self, _socket: Socket | EventFile): ...
    def on_exception(self, exception: BaseException): ...  # type: ignore[override]
    def on_expected(self, exception: BaseException): ...  # type: ignore[override]
    def on_data(self, address: Any, data: bytes): ...
    def ensure_write(self): ...
    def remove_write(self): ...
    def enable_read(self): ...
    def disable_read(self): ...
    def send(
        self,
        data: bytes | str,
        address: Any,
        delay: bool = ...,
        callback: Callable[[DatagramServer], Any] | None = ...,
    ): ...
    def _send(self, _socket: Socket): ...
    def _flush_write(self): ...

class StreamServer(Server):
    def reads(self, reads: Sequence[Socket | EventFile], state: bool = ...): ...
    def writes(self, writes: Sequence[Socket | EventFile], state: bool = ...): ...
    def errors(self, errors: Sequence[Socket | EventFile], state: bool = ...): ...
    def serve(self, type: int = ..., *args, **kwargs): ...  # type: ignore[override]
    def on_read_s(self, _socket: Socket): ...  # type: ignore[override]
    def on_write_s(self, _socket: Socket): ...
    def on_error_s(self, _socket: Socket): ...
    def on_read(self, _socket: Socket | EventFile): ...
    def on_write(self, _socket: Socket | EventFile): ...
    def on_error(self, _socket: Socket | EventFile): ...
    def on_exception(self, exception: BaseException, connection: Connection): ...
    def on_exception_s(self, exception: BaseException): ...
    def on_expected(self, exception: BaseException, connection: Connection): ...
    def on_expected_s(self, exception: BaseException): ...
    def on_upgrade(self, connection: Connection): ...
    def on_ssl(self, connection: Connection): ...
    def on_data(self, connection: Connection, data: bytes): ...
    def on_socket_c(self, socket_c: Socket, address: Any): ...
    def on_socket_d(self, socket_c: Socket): ...
    def _ssl_handshake(self, connection: Connection): ...
