from typing import Any

from netius import Connection, Observable

OPEN: int
CLOSED: int
PENDING: int

class Stream(Observable):
    status: int
    owner: Any
    connection: Connection

    def __init__(self, owner: Any = ...): ...
    def reset(self): ...
    def open(self): ...
    def close(self): ...
    def info_dict(self, full: bool = ...) -> dict[str, Any]: ...
    def is_open(self) -> bool: ...
    def is_closed(self) -> bool: ...
    def is_pending(self) -> bool: ...
