from typing import Any

from .observer import Observable

OPEN: int
CLOSED: int
PENDING: int

class Stream(Observable):
    status: int
    owner: Any | None
    connection: Any | None

    def __init__(self, owner: Any | None = ...): ...
    def reset(self) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def info_dict(self, full: bool = ...) -> dict[str, Any]: ...
    def is_open(self) -> bool: ...
    def is_closed(self) -> bool: ...
    def is_pending(self) -> bool: ...
