from typing import Any, Mapping

def fingerprint(certificate: bytes, hash: str = ...) -> str: ...
def match_fingerprint(certificate: bytes, exp_fingerprint: str, hash: str = ...): ...
def match_hostname(certificate: Mapping[str, Any], hostname: str): ...
def dnsname_match(domain: str, hostname: str, max_wildcards: int = ...) -> bool: ...
def dump_certificate(
    certificate: Mapping[str, Any], certificate_binary: bytes, name: str | None = ...
): ...
