from typing import Any, Callable, Generator

from netius import Connection, ConnectionCompat, Observable, Protocol, Service

class Transport(Observable):
    def __init__(self, loop: Any, connection: Connection, open: bool = ...): ...
    def open(self): ...
    def close(self): ...
    def abort(self): ...
    def write(self, data: bytes | str): ...
    def sendto(self, data: bytes | str, addr: tuple[str, int] | None = ...): ...
    def get_extra_info(self, name: str, default: Any = ...) -> Any: ...
    def get_write_buffer_size(self) -> int: ...
    def get_write_buffer_limits(self) -> tuple[int, int]: ...
    def set_handlers(self): ...
    def set_write_buffer_limits(
        self, high: int | None = ..., low: int | None = ...
    ): ...
    def set_extra_dict(self): ...
    def get_protocol(self) -> Protocol | None: ...
    def set_protocol(self, protocol: Protocol): ...
    def is_closing(self) -> bool: ...
    def _on_data(self, connection: Connection, data: Any): ...
    def _on_close(self, connection: Connection): ...
    def _set_compat(self, protocol: Protocol): ...
    def _set_binds(self): ...
    def _set_protocol(self, protocol: Protocol, mark: bool = ...): ...
    def _buffer_touched(self, connection: Connection): ...
    def _handle_flow(self): ...
    def _cleanup(self): ...
    def _call_connection_lost(self, context: Exception | None): ...
    def _call_soon(self, callback: Callable[..., Any], *args): ...

class TransportDatagram(Transport):
    def _on_data(self, connection: Connection, data: tuple[bytes, tuple[str, int]]): ...
    def _on_close(self, connection: Connection): ...

class TransportStream(Transport, ConnectionCompat):
    @property
    def connection(self) -> Connection | None: ...
    def _on_data(self, connection: Connection, data: bytes): ...
    def _on_close(self, connection: Connection): ...

class ServerTransport(Observable):
    def __init__(self, loop: Any, service: Service, open: bool = ...): ...
    def __aenter__(self) -> Any: ...
    def __aexit__(self, *exc) -> Any: ...
    def open(self): ...
    def close(self): ...
    def get_loop(self) -> Any: ...
    def start_serving(self) -> Any: ...
    def serve_forever(self) -> Any: ...
    def wait_closed(self) -> Any: ...
    def is_serving(self) -> bool: ...
    def _set_compat(
        self,
        protocol_factory: Callable[[], Protocol],
        serve: Callable[[], Any] | None = ...,
    ): ...
    def _set_binds(self): ...
    def _set_protocol_factory(self, protocol_factory: Callable[[], Protocol]): ...
    def _set_serve(self, serve: Callable[[], Any] | None): ...
    def _on_connection(self, connection: Connection): ...
    def _start_serving(self) -> Generator[Any, Any, None]: ...
    def _serve_forever(self) -> Generator[Any, Any, None]: ...
    def _wait_closed(self) -> Generator[Any, Any, None]: ...
    def _aenter(self) -> Generator[Any, Any, None]: ...
    def _aexit(self) -> Generator[Any, Any, None]: ...
