import netius as netius

from typing import Any
from netius.base.legacy import StringIO

class BaseAdapter:
    def set(self, value: Any, owner: str = ...) -> None: ...
    def get(self, key: str) -> str | StringIO: ...
    def get_file(self, key: str, mode: str = ...) -> StringIO: ...
    def delete(self, key: str, owner: str = ...) -> None: ...
    def append(self, key:str , value: Any) -> None: ...
    def truncate(self, key:str , count: int) -> None: ...
    def size(self, key:str ) -> int: ...
    def sizes(self, owner: str | None = ...) -> list[int]: ...
    def total(self, owner: str | None = ...) -> int: ...
    def reserve(self, owner: str = ...) -> None: ...
    def count(self, owner: str | None = ...) -> int: ...
    def list(self, owner: str | None = ...) -> tuple[()]: ...
    def generate(self) -> str: ...
