from os import PathLike

from netius import BaseAdapter

class FsAdapter(BaseAdapter):
    base_path: str

    def __init__(self, base_path: str | None = ...) -> None: ...
    def _path(self, owner: str | None = ...) -> str: ...
    def _ensure(self, owner: str) -> str: ...
    def _symlink(self, source: PathLike[str], target: PathLike[str]) -> None: ...
