from typing import Any, BinaryIO, Callable

from netius import BaseAdapter

class MemoryAdapter(BaseAdapter):
    def __init__(self): ...
    def _ensure(self, owner: str) -> dict[str, Any]: ...
    def _build_close(self, file: BinaryIO, key: str) -> Callable[[], None]: ...
