import netius as netius
import unittest.case
from typing import ClassVar

__version__: str
__revision__: str
__date__: str

class UtilTest(unittest.case.TestCase):
    _classSetupFailed: ClassVar[bool] = ...
    _class_cleanups: ClassVar[list] = ...
    def test_is_ip4(self): ...
    def test_is_ip6(self): ...
    def test_assert_ip4(self): ...
    def test_in_subnet_ip4(self): ...
    def test_addr_to_ip4(self): ...
    def test_addr_to_ip6(self): ...
    def test_bytes_to_integer(self): ...
    def test_integer_to_bytes(self): ...
    def test_size_round_unit(self): ...
    def test_verify(self): ...
    def test_verify_equal(self): ...
    def test_verify_not_equal(self): ...
    def test_verify_type(self): ...
    def test_verify_many(self): ...
