import netius as netius
import unittest.case
from typing import ClassVar

__version__: str
__revision__: str
__date__: str

class HTTPClientTest(unittest.case.TestCase):
    _classSetupFailed: ClassVar[bool] = ...
    _class_cleanups: ClassVar[list] = ...
    def setUp(self): ...
    def test_simple(self): ...
    def test_timeout(self): ...
    def test_compression(self): ...
    def test_headers(self): ...
