from netius.common import HTTP2Parser, HTTP2Stream, HTTPParser
from netius.servers import HTTP2Server, HTTPConnection

class HelloServer(HTTP2Server):
    message: str

    def __init__(self, message: str = ..., *args, **kwargs): ...
    def on_serve(self): ...
    def on_data_http(
        self,
        connection: HTTPConnection | HTTP2Stream,
        parser: HTTPParser | HTTP2Parser | HTTP2Stream | None,
    ): ...
    def _hello_close(self, connection: HTTPConnection): ...
    def _hello_keep(self, connection: HTTPConnection): ...
