from re import Pattern
from typing import Any, Literal, Mapping, Sequence

from netius import AddressAuth, SimpleAuth
from netius.extra import ReverseProxyServer

class ConsulProxyServer(ReverseProxyServer):
    def __init__(
        self,
        consul_url: str = ...,
        consul_token: str | None = ...,
        consul_tag: str = ...,
        consul_poll_interval: float = ...,
        consul_skip_health: bool = ...,
        host_suffixes: Sequence[str] = ...,
        *args,
        **kwargs
    ): ...
    def on_serve(self): ...
    def on_config(self): ...
    def _build_consul(
        self, entries: Sequence[tuple[str, str, Sequence[str], Sequence[str]]]
    ): ...
    def _build_hosts(
        self, entries: Sequence[tuple[str, str, Sequence[str], Sequence[str]]]
    ): ...
    def _build_suffixes(self, alias: bool = ..., redirect: bool = ...): ...
    def _consul_fetch(self) -> list[tuple[str, str, list[str], Sequence[str]]]: ...
    def _consul_tick(self, timeout: float = ...): ...
    def _consul_services(self) -> Mapping[str, Sequence[str]]: ...
    def _consul_health(self, service: str) -> Sequence[Mapping[str, Any]]: ...
    def _consul_get(self, url: str) -> Any: ...
    def _resolve_domain(self, service: str, tags: Sequence[str]) -> str: ...
    def _resolve_address(self, tags: Sequence[str]) -> str | None: ...
    def _resolve_protocol(self, tags: Sequence[str]) -> str: ...
    def _resolve_ports(self, tags: Sequence[str]) -> set[int] | None: ...
    def _resolve_auth_regex(
        self, tags: Sequence[str]
    ) -> list[tuple[Pattern[str], Any]] | None: ...
    def _resolve_redirect(self, value: str) -> str | tuple[str, str] | None: ...
    def _resolve_redirect_regex(
        self, tags: Sequence[str]
    ) -> list[tuple[Pattern[str], str]] | None: ...
    def _resolve_auth_type(
        self, auth_type: str, tags: Sequence[str]
    ) -> SimpleAuth | AddressAuth | Literal[False] | None: ...
    def _resolve_tag(self, tags: Sequence[str], prefix: str) -> str | None: ...
    def _apply_tags(self, domain: str, tags: Sequence[str]): ...
    def _build_urls(
        self,
        instances: Sequence[Mapping[str, Any]],
        address: str | None = ...,
        ports: set[int] | None = ...,
        protocol: str = ...,
    ) -> list[str]: ...
    def _debug_entries(
        self, entries: Sequence[tuple[str, str, Sequence[str], Sequence[str]]]
    ): ...
    def _debug_state(self): ...
    def _debug_auth_regex(
        self, domain: str, auth_regex: Sequence[tuple[Pattern[str], Any]]
    ): ...
    def _debug_redirect_regex(
        self, domain: str, redirect_regex: Sequence[tuple[Pattern[str], str]]
    ): ...
