from typing import Sequence

from netius.extra import ReverseProxyServer

class DockerProxyServer(ReverseProxyServer):
    def __init__(self, host_suffixes: Sequence[str] = ..., *args, **kwargs): ...
    def on_serve(self): ...
    def _build_docker(self): ...
    def _build_regex(self, token: str = ..., sort: bool = ...): ...
    def _build_hosts(self, alias: bool = ...): ...
    def _build_alias(self): ...
    def _build_passwords(self): ...
    def _build_redirect(self): ...
    def _build_error_urls(self): ...
    def _build_redirect_ssl(self, alias: bool = ...): ...
    def _build_suffixes(self, alias: bool = ..., redirect: bool = ...): ...
    def _valid_url(self, value: str) -> bool: ...
