def prime(number_bits: int) -> int: ...
def is_prime(number: int) -> bool: ...
def relatively_prime(first: int, second: int) -> bool: ...
def gcd(first: int, second: int) -> int: ...
def egcd(first: int, second: int) -> tuple[int, int, int]: ...
def modinv(first: int, second: int) -> int: ...
def random_integer_interval(min_value: int, max_value: int) -> int: ...
def random_primality(number: int, k: int) -> bool: ...
def jacobi_witness(x: int, n: int) -> bool: ...
def jacobi(a: int, b: int) -> int: ...
def ceil_integer(value: int | float) -> int: ...
