from typing import Mapping

from netius.common.mime import Headers

def dkim_sign(
    message: bytes,
    selector: str,
    domain: str,
    private_key: Mapping[str, int],
    identity: str | None = ...,
    separator: str = ...,
    creation: float | None = ...,
) -> bytes: ...
def dkim_headers(headers: Headers) -> Headers: ...
def dkim_body(body: bytes) -> bytes: ...
def dkim_header_relaxed(name: bytes, value: bytes) -> bytes: ...
def dkim_header_relaxed_dkim(signature: bytes) -> bytes: ...
def dkim_fold(header: bytes, length: int = ...) -> bytes: ...
def dkim_fold_b(value: bytes, length: int = ...) -> bytes: ...
def dkim_generate(
    domain: str, suffix: str | None = ..., number_bits: int = ...
) -> dict[str, str]: ...
