from contextlib import contextmanager
from typing import IO, Any, Callable, Iterator, Mapping, NoReturn, Sequence

from netius import Stream
from netius.common import HTTPParser, Parser

HEADER_SIZE: int
SETTING_SIZE: int
DATA: int
HEADERS: int
PRIORITY: int
RST_STREAM: int
SETTINGS: int
PUSH_PROMISE: int
PING: int
GOAWAY: int
WINDOW_UPDATE: int
CONTINUATION: int
PROTOCOL_ERROR: int
INTERNAL_ERROR: int
FLOW_CONTROL_ERROR: int
SETTINGS_TIMEOUT: int
STREAM_CLOSED: int
FRAME_SIZE_ERROR: int
REFUSED_STREAM: int
CANCEL: int
COMPRESSION_ERROR: int
CONNECT_ERROR: int
ENHANCE_YOUR_CALM: int
INADEQUATE_SECURITY: int
HTTP_1_1_REQUIRED: int
SETTINGS_HEADER_TABLE_SIZE: int
SETTINGS_ENABLE_PUSH: int
SETTINGS_MAX_CONCURRENT_STREAMS: int
SETTINGS_INITIAL_WINDOW_SIZE: int
SETTINGS_MAX_FRAME_SIZE: int
SETTINGS_MAX_HEADER_LIST_SIZE: int
HTTP_20: int
HEADER_STATE: int
PAYLOAD_STATE: int
FINISH_STATE: int
HTTP2_WINDOW: int
HTTP2_FRAME_SIZE: int
HTTP2_PREFACE: bytes
HTTP2_PSEUDO: tuple[str, ...]
HTTP2_STREAM_ERRORS: tuple[int, ...]
HTTP2_CONNECTION: tuple[str, ...]
HTTP2_TUPLES: tuple[tuple[int, str], ...]
HTTP2_NAMES: Mapping[int, str]
HTTP2_SETTINGS: Mapping[int, int]
HTTP2_SETTINGS_OPTIMAL: Mapping[int, int]
HTTP2_SETTINGS_T: Sequence[tuple[int, int]]
HTTP2_SETTINGS_OPTIMAL_T: Sequence[tuple[int, int]]

class HTTP2Parser(Parser):
    FIELDS: tuple[str, ...]

    def __init__(self, owner: Any, store: bool = ..., file_limit: int = ...): ...
    def build(self): ...
    def destroy(self): ...
    def info_dict(self) -> dict[str, Any]: ...
    def info_streams(self) -> list[dict[str, Any]]: ...
    def reset(self, store: bool = ..., file_limit: int = ...): ...
    def clear(self, force: bool = ..., save: bool = ...): ...
    def close(self): ...
    def parse(self, data: bytes) -> int: ...
    def get_type_s(self, type: int) -> str | None: ...
    def assert_header(self): ...
    def assert_stream(self, stream: HTTP2Stream): ...
    def assert_data(self, stream: HTTP2Stream, end_stream: bool): ...
    def assert_headers(self, stream: HTTP2Stream, end_stream: bool): ...
    def assert_priority(self, stream: HTTP2Stream | None, dependency: int): ...
    def assert_rst_stream(self, stream: HTTP2Stream | None): ...
    def assert_settings(
        self, settings: Sequence[tuple[int, int]], ack: int, extended: bool = ...
    ): ...
    def assert_push_promise(self, promised_stream: int) -> NoReturn: ...
    def assert_ping(self): ...
    def assert_goaway(self): ...
    def assert_window_update(self, stream: HTTP2Stream | None, increment: int): ...
    def assert_continuation(self, stream: HTTP2Stream): ...
    @property
    def type_s(self) -> str | None: ...
    def _parse_header(self, data: bytes) -> int: ...
    def _parse_payload(self, data: bytes) -> int: ...
    def _parse_data(self, data: bytes): ...
    def _parse_headers(self, data: bytes): ...
    def _parse_priority(self, data: bytes): ...
    def _parse_rst_stream(self, data: bytes): ...
    def _parse_settings(self, data: bytes): ...
    def _parse_push_promise(self, data: bytes): ...
    def _parse_ping(self, data: bytes): ...
    def _parse_goaway(self, data: bytes): ...
    def _parse_window_update(self, data: bytes): ...
    def _parse_continuation(self, data: bytes): ...
    def _has_stream(self, stream: int) -> bool: ...
    def _get_stream(
        self,
        stream: int | None = ...,
        default: HTTP2Stream | None = ...,
        strict: bool = ...,
        closed_s: bool = ...,
        unopened_s: bool = ...,
        exists_s: bool = ...,
    ) -> HTTP2Stream | None: ...
    def _set_stream(self, stream: HTTP2Stream): ...
    def _del_stream(self, stream: int): ...
    def _invalid_type(self) -> NoReturn: ...
    @property
    def buffer_size(self) -> int: ...
    @property
    def buffer_data(self, empty: bool = ...) -> bytes: ...
    @property
    def encoder(self) -> Any: ...
    @property
    def decoder(self) -> Any: ...

class HTTP2Stream(Stream):
    identifier: int | None
    header_b: list[bytes]
    dependency: int
    weight: int
    exclusive: bool
    end_headers: bool
    end_stream: bool
    end_stream_l: bool

    def __init__(
        self,
        identifier: int | None = ...,
        header_b: bytes | None = ...,
        dependency: int = ...,
        weight: int = ...,
        exclusive: bool = ...,
        end_headers: bool = ...,
        end_stream: bool = ...,
        end_stream_l: bool = ...,
        store: bool = ...,
        file_limit: int = ...,
        window: int = ...,
        frame_size: int = ...,
        *args,
        **kwargs
    ): ...
    def __getattr__(self, name: str) -> Any: ...
    def reset(
        self,
        store: bool = ...,
        file_limit: int = ...,
        window: int = ...,
        frame_size: int = ...,
    ): ...
    def open(self): ...
    def close(self, flush: bool = ..., destroy: bool = ..., reset: bool = ...): ...
    def info_dict(self, full: bool = ...) -> dict[str, Any]: ...
    def available(self): ...
    def unavailable(self): ...
    def resolve_encoding(self, parser: HTTPParser | HTTP2Stream): ...
    def encoding_w(self) -> int: ...
    def encoding_name(self) -> str | None: ...
    def set_encoding(self, encoding: int): ...
    def set_base(self): ...
    def set_uncompressed(self): ...
    def set_plain(self): ...
    def set_chunked(self): ...
    def set_gzip(self): ...
    def set_deflate(self): ...
    def is_plain(self) -> bool: ...
    def is_chunked(self) -> bool: ...
    def is_gzip(self) -> bool: ...
    def is_deflate(self) -> bool: ...
    def is_compressed(self) -> bool: ...
    def is_uncompressed(self) -> bool: ...
    def is_dynamic(self) -> bool: ...
    def is_flushed(self) -> bool: ...
    def is_measurable(self, strict: bool = ...) -> bool: ...
    def is_exhausted(self) -> bool: ...
    def is_restored(self) -> bool: ...
    def decode_headers(self, force: bool = ..., assert_h: bool = ...): ...
    def extend_headers(self, fragment: bytes): ...
    def extend_data(self, data: bytes): ...
    def remote_update(self, increment: int): ...
    def local_update(self, increment: int): ...
    def get_path(self, normalize: bool = ...) -> str: ...
    def get_query(self) -> str: ...
    def get_message_b(self, copy: bool = ..., size: int = ...) -> IO[bytes]: ...
    def get_encodings(self) -> Sequence[str]: ...
    def fragment(self, data: bytes) -> Iterator[bytes]: ...
    def fragmentable(self, data: bytes) -> bool: ...
    def flush(self, *args, **kwargs) -> int | None: ...
    def flush_s(self, *args, **kwargs) -> int: ...
    def send_response(self, *args, **kwargs) -> int: ...
    def send_header(self, *args, **kwargs) -> int: ...
    def send_part(self, *args, **kwargs) -> int: ...
    def send_reset(self, *args, **kwargs) -> int: ...
    def assert_headers(self): ...
    def assert_ready(self): ...
    @contextmanager
    def ctx_request(
        self, args: tuple[Any, ...] | None = ..., kwargs: dict[str, Any] | None = ...
    ) -> Iterator[None]: ...
    @property
    def parser(self) -> HTTP2Stream: ...
    @property
    def is_ready(self, calculate: bool = ..., assert_r: bool = ...) -> bool: ...
    @property
    def is_headers(self) -> bool: ...
    def _calculate(self): ...
    def _calculate_headers(self): ...
    def _build_b(self) -> IO[bytes]: ...
    def _build_c(
        self, callback: Callable[[HTTP2Stream], Any], validate: bool = ...
    ) -> Callable[[Any], None]: ...
    def _parse_query(self, query: str) -> Mapping[str, Sequence[str]]: ...
    def _decode_params(
        self, params: Mapping[str | bytes, Sequence[str | bytes]]
    ) -> Mapping[str, Sequence[str]]: ...
