from re import Pattern
from typing import Any

LINE_REGEX: Pattern[bytes]
SPACE_REGEX: Pattern[bytes]
HEADER_NAME_REGEX: Pattern[bytes]
MIME_TYPES: tuple[tuple[str, str], ...]
MIME_REGISTERED: bool

class Headers(list):
    def __getitem__(self, key: int | bytes) -> Any: ...  # type: ignore[override]
    def __setitem__(self, key: bytes | str, value: Any): ...  # type: ignore[override]
    def __delitem__(self, key: int | bytes): ...  # type: ignore[override]
    def __contains__(self, item: Any) -> bool: ...
    def item(self, key: bytes) -> list[bytes]: ...
    def get(self, key: bytes, default: Any = ...) -> Any: ...
    def set(self, key: bytes | str, value: Any, append: bool = ...): ...
    def pop(self, key: bytes | str, default: Any = ...) -> Any: ...  # type: ignore[override]
    def join(self, separator: bytes | str = ...) -> bytes: ...
    def _normalize(self, value: Any) -> bytes: ...

def rfc822_parse(message: bytes, strip: bool = ...) -> tuple[Headers, bytes]: ...
def rfc822_join(headers: Headers, body: bytes) -> bytes: ...
def mime_register(): ...
