from typing import Any, Mapping, Self

from netius import Observable

class Parser(Observable):
    FIELDS: tuple[str, ...]
    owner: Any

    def __init__(self, owner: Any): ...
    @classmethod
    def mock(cls, owner: Any, state: Mapping[str, Any]) -> Self: ...
    def build(self): ...
    def destroy(self): ...
    def get_state(self) -> dict[str, Any]: ...
    def set_state(self, state: Mapping[str, Any]): ...
    def info_dict(self) -> dict[str, Any]: ...
    def parse(self, data: bytes): ...
