from os import PathLike
from typing import IO, Mapping

PRIVATE_TOKEN: str
PUBLIC_TOKEN: str

def open_pem_key(path: str | IO[bytes], token: str = ...) -> bytes: ...
def open_pem_data(data: bytes, token: str = ...) -> bytes: ...
def write_pem_key(
    path: str | IO[bytes], data: bytes, token: str = ..., width: int = ...
): ...
def open_private_key(path: str | IO[bytes]) -> dict[str, int]: ...
def open_private_key_b64(data_b64: str | bytes) -> dict[str, int]: ...
def open_private_key_data(data: bytes) -> dict[str, int]: ...
def open_public_key(path: str | IO[bytes]) -> dict[str, int]: ...
def open_public_key_b64(data_b64: str | bytes) -> dict[str, int]: ...
def open_public_key_data(data: bytes) -> dict[str, int]: ...
def write_private_key(path: str | IO[bytes], private_key: Mapping[str, int]): ...
def write_public_key(path: str | IO[bytes], public_key: Mapping[str, int]): ...
def asn_private_key(private_key: Mapping[str, int]) -> bytes: ...
def asn_public_key(public_key: Mapping[str, int]) -> bytes: ...
def pem_to_der(in_path: str | IO[bytes], out_path: PathLike[str], token: str = ...): ...
def pem_limiters(token: str) -> tuple[bytes, bytes]: ...
def private_to_public(private_key: Mapping[str, int]) -> dict[str, int]: ...
def assert_private(private_key: Mapping[str, int], number_bits: int | None = ...): ...
def rsa_private(number_bits: int) -> dict[str, int]: ...
def rsa_primes(number_bits: int) -> tuple[int, int]: ...
def rsa_exponents(
    prime_1: int, prime_2: int, number_bits: int, basic: bool = ...
) -> tuple[int, int]: ...
def rsa_bits(modulus: int) -> int: ...
def rsa_sign(message: str | bytes, private_key: Mapping[str, int]) -> bytes: ...
def rsa_verify(signature: str | bytes, public_key: Mapping[str, int]) -> bytes: ...
def rsa_crypt_s(message: bytes, exponent: int, modulus: int) -> bytes: ...
def rsa_crypt(number: int, exponent: int, modulus: int) -> int: ...
