from typing import Any

from netius.common import Parser

IPV4: int
IPV6: int
DOMAIN: int
VERSION_STATE: int
HEADER_STATE: int
USER_ID_STATE: int
DOMAIN_STATE: int
AUTH_COUNT_STATE: int
AUTH_METHODS_STATE: int
HEADER_EXTRA_STATE: int
SIZE_STATE: int
ADDRESS_STATE: int
PORT_STATE: int
FINISH_STATE: int

class SOCKSParser(Parser):
    def __init__(self, owner: Any): ...
    def build(self): ...
    def destroy(self): ...
    def reset(self): ...
    def clear(self, force: bool = ...): ...
    def parse(self, data: bytes) -> int: ...
    def get_host(self) -> str | None: ...
    def get_address(self) -> bytes | None: ...
    def _parse_version(self, data: bytes) -> int: ...
    def _parse_header(self, data: bytes) -> int: ...
    def _parse_user_id(self, data: bytes) -> int: ...
    def _parse_domain(self, data: bytes) -> int: ...
    def _parse_auth_count(self, data: bytes) -> int: ...
    def _parse_auth_methods(self, data: bytes) -> int: ...
    def _parse_header_extra(self, data: bytes) -> int: ...
    def _parse_size(self, data: bytes) -> int: ...
    def _parse_address(self, data: bytes) -> int: ...
    def _parse_port(self, data: bytes) -> int: ...
