from typing import Any, BinaryIO, Mapping, Sequence

class Stream:
    def open(self, mode: str = ...): ...
    def close(self): ...
    def seek(self, offset: int): ...
    def read(self, size: int) -> bytes: ...
    def write(self, data: bytes): ...
    def flish(self): ...

class FileStream(Stream):
    path: str
    size: int
    file: BinaryIO | None

    def __init__(self, path: str, size: int): ...
    def open(self, mode: str = ..., allocate: bool = ...): ...
    def close(self): ...
    def seek(self, offset: int): ...
    def read(self, size: int) -> bytes: ...
    def write(self, data: bytes): ...
    def flush(self): ...

class FilesStream(Stream):
    dir_path: str
    size: int
    files_m: Sequence[Mapping[str, Any]]
    files: list[tuple[BinaryIO, Mapping[str, Any]]]

    def __init__(
        self, dir_path: str, size: int, files_m: Sequence[Mapping[str, Any]]
    ): ...
    def open(self, mode: str = ..., allocate: bool = ...): ...
    def close(self): ...
    def seek(self, offset: int): ...
    def read(self, size: int) -> bytes: ...
    def write(self, data: bytes): ...
    def flush(self): ...
