from typing import Any, BinaryIO, Iterator

class PriorityDict(dict[Any, Any]):
    def __init__(self, *args, **kwargs): ...
    def __setitem__(self, key: Any, val: Any): ...
    def smallest(self) -> Any: ...
    def pop_smallest(self) -> Any: ...
    def setdefault(self, key: Any, val: Any) -> Any: ...  # type: ignore[override]
    def update(self, *args, **kwargs): ...
    def sorted_iter(self) -> Iterator[Any]: ...
    def _rebuild_heap(self): ...

def file_iterator(
    file_object: BinaryIO, chunk_size: int = ...
) -> Iterator[int | bytes]: ...
