from ssl import SSLContext
from typing import Sequence

from netius import Base

class TLSContextDict(dict[str, tuple[SSLContext, dict[str, str]]]):
    owner: Base
    mtimes: dict[str, float]
    domains: set[str]

    def __init__(self, owner: Base, domains: Sequence[str], *args, **kwargs): ...
    def load(self, domains: Sequence[str]): ...
    def reload(self, domains: Sequence[str] | None = ...) -> bool: ...
    def has_definition(self, domain: str) -> bool: ...
    def cer_path(self, domain: str) -> str: ...
    def key_path(self, domain: str) -> str: ...
    def _mtime(self, domain: str) -> float: ...

class LetsEncryptDict(TLSContextDict):
    letse_path: str

    def __init__(self, owner: Base, domains: Sequence[str], *args, **kwargs): ...
    def cer_path(self, domain: str) -> str: ...
    def key_path(self, domain: str) -> str: ...
