from re import Pattern
from typing import Any, Iterator, Mapping

from netius import Connection
from netius.common import Parser

HANDSHAKE_SIZE: int
DECIMAL_REGEX: Pattern[str]
TORRENT_TYPES: Mapping[int, str]

def info_hash(root: Mapping[str, Any]) -> bytes: ...
def bencode(root: Any) -> bytes: ...
def bdecode(data: bytes | str) -> Any: ...
def chunk(item: Any) -> Iterator[bytes]: ...
def dechunk(chunks: list[str]) -> Any: ...

class TorrentParser(Parser):
    length: int | None
    buffer: list[bytes]
    buffer_l: int

    def __init__(self, owner: Connection, store: bool = ...): ...
    def build(self): ...
    def destroy(self): ...
    def parse(self, data: bytes) -> int: ...
    def _join(self, data: bytes) -> bytes: ...
    def _parse_handshake(self, data: bytes) -> int: ...
    def _parse_message(self, data: bytes) -> int: ...
