from typing import Any, Generator, Sequence

SIZE_UNITS_LIST: tuple[str, ...]
SIZE_UNITS_LIST_S: tuple[str, ...]
SIZE_UNIT_COEFFICIENT: int
DEFAULT_MINIMUM: int
DEFAULT_PLACES: int
FILE_ATTRIBUTE_REPARSE_POINT: int

def cstring(value: str) -> str: ...
def chunks(
    sequence: Sequence[Any], count: int
) -> Generator[Sequence[Any], None, None]: ...
def header_down(name: str) -> str: ...
def header_up(name: str) -> str: ...
def is_ip4(address: str) -> bool: ...
def is_ip6(address: str) -> bool: ...
def assert_ip4(
    address: str, allowed: Sequence[str] | None, default: bool = ...
) -> bool: ...
def in_subnet_ip4(address: str, subnet: str) -> bool: ...
def addr_to_ip4(number: int) -> str: ...
def addr_to_ip6(number: int) -> str: ...
def ip4_to_addr(value: str) -> int: ...
def string_to_bits(value: bytes) -> str: ...
def integer_to_bytes(number: int, length: int = ...) -> bytes: ...
def bytes_to_integer(bytes: bytes) -> int: ...
def random_integer(number_bits: int) -> int: ...
def host(default: str = ...) -> str: ...
def hostname() -> str: ...
def is_sub_path(base_path: str, path: str, follow_links: bool = ...) -> bool: ...
def size_round_unit(
    size_value: int | float,
    minimum: int = ...,
    places: int = ...,
    reduce: bool = ...,
    space: bool = ...,
    justify: bool = ...,
    simplified: bool = ...,
    depth: int = ...,
) -> str: ...
def verify(
    condition: Any, message: str | None = ..., exception: type[Exception] | None = ...
): ...
def verify_equal(
    first: Any,
    second: Any,
    message: str | None = ...,
    exception: type[Exception] | None = ...,
): ...
def verify_not_equal(
    first: Any,
    second: Any,
    message: str | None = ...,
    exception: type[Exception] | None = ...,
): ...
def verify_type(
    value: Any,
    types: type[Any] | tuple[type[Any], ...],
    null: bool = ...,
    message: str | None = ...,
    exception: type[Exception] | None = ...,
    **kwargs
): ...
def verify_many(
    sequence: Sequence[Any],
    message: str | None = ...,
    exception: type[Exception] | None = ...,
): ...
