def encode_ws(
    data: bytes | str, final: bool = ..., opcode: int = ..., mask: bool = ...
) -> bytes: ...
def decode_ws(data: bytes) -> tuple[bytes, bytes]: ...
def assert_ws(data_l: int, size: int): ...
