"""
This type stub file was generated by pyright.
"""

from . import dhcp, echo, echo_ws, ftp, http, http2, mjpg, pop, proxy, smtp, socks, tftp, torrent, ws, wsgi
from .dhcp import DHCPRequest, DHCPServer
from .echo_ws import EchoWSServer
from .echo import EchoServer
from .ftp import FTPConnection, FTPServer
from .http import HTTPConnection, HTTPServer
from .http2 import HTTP2Server
from .mjpg import MJPGServer
from .pop import POPConnection, POPServer
from .proxy import ProxyConnection, ProxyServer
from .smtp import SMTPConnection, SMTPServer, TERMINATION_SIZE
from .socks import SOCKSConnection, SOCKSServer
from .tftp import TFTPRequest, TFTPServer
from .torrent import Pieces, TorrentServer, TorrentTask
from .ws import WSConnection, WSServer
from .wsgi import WSGIServer

__version__ = ...
__revision__ = ...
__date__ = ...
__copyright__ = ...
__license__ = ...
