import netius as netius
import netius.servers.http2
import netius.servers.http2 as http2

__version__: str
__revision__: str
__date__: str
BOUNDARY: str

class MJPGServer(netius.servers.http2.HTTP2Server):
    def __init__(self, boundary: str = ..., *args, **kwargs) -> None: ...
    def on_data_http(self, connection, parser): ...
    def on_send_mjpg(self, connection): ...
    def get_delay(self, connection): ...
    def get_image(self, connection): ...
