import netius as netius
import netius.sh.base as base

__version__: str
__revision__: str
__date__: str
def read_private(path): ...
def read_public(path): ...
def private_to_public(private_path, public_path): ...
