"""
This type stub file was generated by pyright.
"""

from . import agent, asynchronous, client, common, compat, config, conn, container, errors, legacy, log, observer, poll, protocol, request, server, stream, tls, transport, util
from .agent import Agent, ClientAgent, ServerAgent
from .asynchronous import Executor, Future, Handle, Task, ThreadPoolExecutor, async_test, async_test_all, coroutine, coroutine_return, ensure_generator, get_asyncio, is_asynclib, is_await, is_coroutine, is_coroutine_native, is_coroutine_object, is_future, is_neo, notify, sleep, wait, wakeup
from .client import Client, DatagramClient, StreamClient
from .common import Base, BaseThread, IDENTIFIER, IDENTIFIER_LONG, IDENTIFIER_SHORT, NAME, SSL_CA_PATH, SSL_CER_PATH, SSL_DH_PATH, SSL_KEY_PATH, TCP_TYPE, UDP_TYPE, VERSION, build_future, compat_loop, ensure, ensure_asyncio, ensure_loop, ensure_main, ensure_pool, get_event_loop, get_loop, get_main, get_poll, new_loop, new_loop_asyncio, new_loop_main, stop_loop
from .compat import BaseLoop, CompatLoop, build_datagram, connect_stream, is_asyncio, is_compat
from .config import conf, conf_ctx, conf_d, conf_prefix, conf_r, conf_s, conf_suffix
from .conn import CHUNK_SIZE, CLOSED, Connection, OPEN, PENDING
from .container import Container, ContainerServer
from .errors import AssertionError, DataError, GeneratorError, NetiusError, NotImplemented, ParserError, PauseError, RuntimeError, SecurityError, StopError, WakeupError
from .log import SILENT, rotating_handler, smtp_handler
from .observer import Observable
from .poll import EpollPoll, KqueuePoll, Poll, PollPoll, SelectPoll
from .protocol import DatagramProtocol, Protocol, StreamProtocol
from .request import Request, Response
from .server import DatagramServer, Server, StreamServer
from .stream import Stream
from .tls import dnsname_match, dump_certificate, fingerprint, match_fingerprint, match_hostname
from .transport import Transport, TransportDatagram, TransportStream
from .util import camel_to_underscore, verify

__version__ = ...
__revision__ = ...
__date__ = ...
__copyright__ = ...
__license__ = ...
