import netius as netius
import netius.mock.appier
import netius.mock.appier as appier
from typing import ClassVar

__version__: str
__revision__: str
__date__: str
loaded: bool

class DiagApp(netius.mock.appier.APIApp):
    show_logger: ClassVar[None] = ...
    set_logger: ClassVar[None] = ...
    show_environ: ClassVar[None] = ...
    system_info: ClassVar[None] = ...
    list_connections: ClassVar[None] = ...
    show_connection: ClassVar[None] = ...
    def __init__(self, system, *args, **kwargs) -> None: ...
