from _typeshed import Incomplete

__version__: str
__revision__: str
__date__: str

class Observable:
    def __init__(self, *args, **kwargs) -> None: ...
    def build(self): ...
    def destroy(self): ...
    def bind(self, name, method, oneshot: bool = ...): ...
    def unbind(self, name, method: Incomplete | None = ...): ...
    def unbind_all(self): ...
    def trigger(self, name, *args, **kwargs): ...
