import netius.base.config as config
import netius.base.errors as errors
from _typeshed import Incomplete

__version__: str
__revision__: str
__date__: str
def fingerprint(certificate, hash: str = ...): ...
def match_fingerprint(certificate, exp_fingerprint, hash: str = ...): ...
def match_hostname(certificate, hostname): ...
def dnsname_match(domain, hostname, max_wildcards: int = ...): ...
def dump_certificate(certificate, certificate_binary, name: Incomplete | None = ...): ...
