"""
This type stub file was generated by pyright.
"""

from . import desktop, dhcp_s, file, filea, hello, hello_w, proxy_d, proxy_f, proxy_r, smtp_r
from .desktop import DesktopServer
from .dhcp_s import DHCPServerS
from .file import FileServer
from .filea import FileAsyncServer
from .hello import HelloServer
from .proxy_d import DockerProxyServer
from .proxy_f import ForwardProxyServer
from .proxy_r import ReverseProxyServer
from .smtp_r import RelaySMTPServer

__version__ = ...
__revision__ = ...
__date__ = ...
__copyright__ = ...
__license__ = ...
