import netius as netius
import netius.servers.dhcp
from _typeshed import Incomplete

__version__: str
__revision__: str
__date__: str

class DHCPServerS(netius.servers.dhcp.DHCPServer):
    def __init__(self, pool: Incomplete | None = ..., options: dict = ..., *args, **kwargs) -> None: ...
    def get_type(self, request): ...
    def get_options(self, request): ...
    def get_yiaddr(self, request): ...
    def _build(self, options): ...
    def _reserve(self, request): ...
    def _confirm(self, request): ...
