"""
This type stub file was generated by pyright.
"""

from . import file as _file

__author__ = ...
__version__ = ...
__revision__ = ...
__date__ = ...
__copyright__ = ...
__license__ = ...
BUFFER_SIZE = ...
class FileAsyncServer(_file.FileServer):
    """
    Simple implementation of a file server that uses the async
    file pool infra-structure.

    This is a test implementation and should never be used for
    production work that required mature and stable codebase.

    Using this kind of server (file pool based) is not recommended
    for system that don't provide some system of event fd (eg: windows)
    as it would provide very slow performance or even stall the
    event loop as no notification occurs on events.
    """
    def on_connection_d(self, connection): # -> None:
        ...
    
    def on_stream_d(self, stream): # -> None:
        ...
    


if __name__ == "__main__":
    server = ...
else:
    __path__ = ...
