import netius as netius
import netius.servers.http2

__version__: str
__revision__: str
__date__: str

class HelloServer(netius.servers.http2.HTTP2Server):
    def __init__(self, message: str = ..., *args, **kwargs) -> None: ...
    def on_serve(self): ...
    def on_data_http(self, connection, parser): ...
    def _hello_close(self, connection): ...
    def _hello_keep(self, connection): ...
