"""
This type stub file was generated by pyright.
"""

import netius.servers

__author__ = ...
__version__ = ...
__revision__ = ...
__date__ = ...
__copyright__ = ...
__license__ = ...
class HelloServer(netius.servers.HTTP2Server):
    """
    Simple Hello (World) HTTP server meant to be used for benchmarks
    and other operations that require a simple in-memory HTTP server.

    Most of the implementation on the server is done in the upper
    layers from which this server class inherits.

    Performance should always be considered critical when changing
    or adding new features to this server implementation.
    """
    def __init__(self, message=..., *args, **kwargs) -> None:
        ...
    
    def on_serve(self): # -> None:
        ...
    
    def on_data_http(self, connection, parser): # -> None:
        ...
    


if __name__ == "__main__":
    server = ...
else:
    __path__ = ...
