import netius as netius
import netius.servers.smtp
from _typeshed import Incomplete

__version__: str
__revision__: str
__date__: str

class RelaySMTPServer(netius.servers.smtp.SMTPServer):
    def __init__(self, *args, **kwargs) -> None: ...
    def on_serve(self): ...
    def on_header_smtp(self, connection, from_l, to_l): ...
    def on_data_smtp(self, connection, data): ...
    def on_message_smtp(self, connection): ...
    def relay(self, connection, froms, tos, contents): ...
    def date(self): ...
    def message_id(self, connection, email: str = ...): ...
    def dkim_contents(self, contents, email: str = ..., creation: Incomplete | None = ...): ...
