from asyncio import AbstractEventLoop
from typing import Any, Callable, Coroutine, Mapping, Sequence

from netius import Connection
from netius.common import HTTP2Parser, HTTP2Stream, HTTPParser
from netius.servers import HTTP2Server, HTTPConnection

ASGI_VERSION: str
SPEC_VERSION: str
LIFESPAN_VERSION: str
COMPRESSED_LIMIT: int
MAX_PENDING: int
BUFFER_SIZE: int
PUMP_LIMIT: int
LIFESPAN_TIMEOUT: float
LIFESPAN_INTERVAL: float
CONTINUATION_OPCODE: int
TEXT_OPCODE: int
BINARY_OPCODE: int
CLOSE_OPCODE: int
PING_OPCODE: int
PONG_OPCODE: int
CLOSE_CODE: int
CLOSE_NONE: int
CLOSE_REJECT: int

class ASGIServer(HTTP2Server):
    app: Callable[..., Any]
    mount: str
    mount_l: int
    compressed_limit: int
    max_pending: int
    lifespan: bool
    asyncio: bool
    loop_asyncio: AbstractEventLoop | None
    pumping: bool
    legacy_app: bool
    lifespan_t: Any
    lifespan_v: str | None
    lifespan_m: str | None
    lifespan_f: Any
    lifespan_q: list[dict[str, Any]]

    def __init__(
        self,
        app: Callable[..., Any],
        mount: str = ...,
        compressed_limit: int = ...,
        max_pending: int = ...,
        lifespan: bool = ...,
        asyncio: bool | None = ...,
        *args,
        **kwargs
    ): ...
    def cleanup(self): ...
    def ticks(self): ...
    def on_connection_c(self, connection: Connection): ...
    def on_connection_d(self, connection: Connection): ...
    def on_serve(self): ...
    def on_stop(self): ...
    def on_data(self, connection: Connection, data: bytes): ...
    def on_data_http(
        self,
        connection: HTTPConnection | HTTP2Stream,
        parser: HTTPParser | HTTP2Parser | HTTP2Stream | None,
    ): ...
    def on_scope(
        self,
        connection: HTTPConnection | HTTP2Stream,
        scope: dict[str, Any],
        body: Any = ...,
    ): ...
    def on_data_ws(
        self, connection: Connection, opcode: int, data: bytes, final: bool = ...
    ): ...
    def _next_queue(self, connection: HTTPConnection | HTTP2Stream): ...
    def _build_scope(
        self,
        connection: HTTPConnection | HTTP2Stream,
        parser: HTTPParser | HTTP2Parser | HTTP2Stream,
    ) -> dict[str, Any]: ...
    def _build_scope_ws(
        self,
        connection: HTTPConnection | HTTP2Stream,
        parser: HTTPParser | HTTP2Parser | HTTP2Stream,
    ) -> dict[str, Any]: ...
    def _build_receive(
        self, connection: HTTPConnection | HTTP2Stream
    ) -> Callable[[], Coroutine[Any, Any, dict[str, Any]]]: ...
    def _build_send(
        self, connection: HTTPConnection | HTTP2Stream
    ) -> Callable[[Mapping[str, Any]], Coroutine[Any, Any, None]]: ...
    def _send(
        self, connection: HTTPConnection | HTTP2Stream, message: Mapping[str, Any]
    ) -> Any: ...
    def _send_start(
        self, connection: HTTPConnection | HTTP2Stream, message: Mapping[str, Any]
    ): ...
    def _send_body(
        self, connection: HTTPConnection | HTTP2Stream, message: Mapping[str, Any]
    ) -> Any: ...
    def _send_accept(
        self, connection: HTTPConnection | HTTP2Stream, message: Mapping[str, Any]
    ): ...
    def _send_ws(
        self, connection: HTTPConnection | HTTP2Stream, message: Mapping[str, Any]
    ) -> Any: ...
    def _send_close(
        self, connection: HTTPConnection | HTTP2Stream, message: Mapping[str, Any]
    ): ...
    def _send_pressure(
        self,
        connection: HTTPConnection | HTTP2Stream,
        data: bytes,
        raw: bool = ...,
    ) -> Any: ...
    def _resolve(self, future: Any): ...
    def _push(
        self, connection: HTTPConnection | HTTP2Stream, message: Mapping[str, Any]
    ): ...
    def _message_body(
        self, connection: HTTPConnection | HTTP2Stream
    ) -> dict[str, Any]: ...
    def _on_task(self, connection: HTTPConnection | HTTP2Stream, future: Any): ...
    def _send_error(self, connection: HTTPConnection | HTTP2Stream): ...
    def _log_exception(self, exception: BaseException): ...
    def _disconnect(self, connection: HTTPConnection | HTTP2Stream): ...
    def _final(self, connection: HTTPConnection | HTTP2Stream): ...
    def _close(self, connection: HTTPConnection | HTTP2Stream): ...
    def _release(self, connection: HTTPConnection | HTTP2Stream): ...
    def _release_task(self, connection: HTTPConnection | HTTP2Stream): ...
    def _release_body(self, connection: HTTPConnection | HTTP2Stream): ...
    def _release_scope(self, connection: HTTPConnection | HTTP2Stream): ...
    def _release_parser(self, connection: HTTPConnection | HTTP2Stream): ...
    def _release_queue(self, connection: HTTPConnection | HTTP2Stream): ...
    def _start_lifespan(self): ...
    def _stop_lifespan(self): ...
    def _wait_lifespan(self, name: str): ...
    def _build_receive_lifespan(
        self,
    ) -> Callable[[], Coroutine[Any, Any, dict[str, Any]]]: ...
    def _build_send_lifespan(
        self,
    ) -> Callable[[Mapping[str, Any]], Coroutine[Any, Any, None]]: ...
    def _push_lifespan(self, message: Mapping[str, Any]): ...
    def _lifespan_m(self) -> str: ...
    def _on_lifespan(self, future: Any): ...
    def _ensure(self, coroutine: Coroutine[Any, Any, Any]) -> Any: ...
    def _future(self) -> Any: ...
    def _pump(self, limit: int = ...): ...
    def _is_ready(self, loop: AbstractEventLoop) -> bool: ...
    def _running_loop(self, asyncio: Any) -> AbstractEventLoop | None: ...
    def _set_running_loop(self, asyncio: Any, loop: AbstractEventLoop | None): ...
    def _call_app(
        self,
        scope: Mapping[str, Any],
        receive: Callable[..., Any],
        send: Callable[..., Any],
    ) -> Coroutine[Any, Any, Any]: ...
    def _accept_key(self, parser: HTTPParser | HTTP2Parser | HTTP2Stream) -> str: ...
    def _headers(
        self, parser: HTTPParser | HTTP2Parser | HTTP2Stream
    ) -> list[tuple[bytes, bytes]]: ...
    def _headers_map(
        self, headers: Sequence[tuple[bytes, bytes]]
    ) -> dict[str, str | list[str]]: ...
    def _subprotocols(
        self, parser: HTTPParser | HTTP2Parser | HTTP2Stream
    ) -> list[str]: ...
    def _version(self, parser: HTTPParser | HTTP2Parser | HTTP2Stream) -> str: ...
    def _close_code(self, data: bytes) -> int: ...
    def _get_buffer(
        self, connection: HTTPConnection | HTTP2Stream, delete: bool = ...
    ) -> bytes: ...
    def _is_upgrade(
        self,
        connection: HTTPConnection | HTTP2Stream,
        parser: HTTPParser | HTTP2Parser | HTTP2Stream,
    ) -> bool: ...
    def _is_upgraded(self, connection: HTTPConnection | HTTP2Stream) -> bool: ...
    def _is_ws(self, connection: HTTPConnection | HTTP2Stream) -> bool: ...
    @classmethod
    def _is_legacy(cls, app: Callable[..., Any]) -> bool: ...
    def _decode(self, value: str) -> str: ...

async def hello_app(
    scope: Mapping[str, Any],
    receive: Callable[..., Any],
    send: Callable[..., Any],
): ...
def load_app(value: str) -> Callable[..., Any]: ...
