from typing import Any, Callable, Mapping, Sequence

from netius import DatagramServer

class DHCPRequest:
    options_m: tuple[Callable[..., bytes], ...] | None
    options_l: int | None
    data: bytes

    def __init__(self, data: bytes): ...
    @classmethod
    def generate(cls): ...
    def get_info(self) -> str: ...
    def print_info(self): ...
    def parse(self): ...
    def unpack_options(self): ...
    def get_requested(self) -> str: ...
    def get_type(self) -> int: ...
    def get_type_s(self) -> str | None: ...
    def get_mac(self) -> str: ...
    def response(
        self, yiaddr: str, options: Mapping[int, Mapping[str, Any] | None] = ...
    ) -> bytes: ...
    @classmethod
    def _str(cls, data: bytes | str) -> bytes: ...
    @classmethod
    def _pack_m(cls, sequence: Sequence[int], format: str) -> bytes: ...
    @classmethod
    def _option_subnet(cls, subnet: str = ...) -> bytes: ...
    @classmethod
    def _option_router(cls, routers: Sequence[str] = ...) -> bytes: ...
    @classmethod
    def _option_dns(cls, servers: Sequence[str] = ...) -> bytes: ...
    @classmethod
    def _option_name(cls, name: str = ...) -> bytes: ...
    @classmethod
    def _option_broadcast(cls, broadcast: str = ...) -> bytes: ...
    @classmethod
    def _option_requested(cls, ip: str = ...) -> bytes: ...
    @classmethod
    def _option_lease(cls, time: int = ...) -> bytes: ...
    @classmethod
    def _option_discover(cls) -> bytes: ...
    @classmethod
    def _option_offer(cls) -> bytes: ...
    @classmethod
    def _option_request(cls) -> bytes: ...
    @classmethod
    def _option_decline(cls) -> bytes: ...
    @classmethod
    def _option_ack(cls) -> bytes: ...
    @classmethod
    def _option_nak(cls) -> bytes: ...
    @classmethod
    def _option_identifier(cls, identifier: str = ...) -> bytes: ...
    @classmethod
    def _option_renewal(cls, time: int = ...) -> bytes: ...
    @classmethod
    def _option_rebind(cls, time: int = ...) -> bytes: ...
    @classmethod
    def _option_proxy(cls, url: str = ...) -> bytes: ...
    @classmethod
    def _option_end(cls) -> bytes: ...

class DHCPServer(DatagramServer):
    def serve(  # type: ignore[override]
        self, port: int = ..., type: int = ..., *args, **kwargs
    ): ...
    def on_data(self, address: Any, data: bytes): ...
    def on_data_dhcp(self, address: Any, request: DHCPRequest): ...
    def get_verb(self, type_r: int) -> str: ...
    def send_dhcp(self, data: bytes, *args, **kwargs): ...
    def get_type(self, request: DHCPRequest) -> int: ...
    def get_options(
        self, request: DHCPRequest
    ) -> dict[int, Mapping[str, Any] | None]: ...
    def get_yiaddr(self, request: DHCPRequest) -> str: ...
