from os import stat_result
from socket import socket
from typing import Any, Callable, Mapping, Sequence

from netius import Connection, ContainerServer, StreamServer
from netius.common import FTPParser

BUFFER_SIZE: int
CAPABILITIES: tuple[str, ...]
PERMISSIONS: Mapping[int, str]
TYPES: Mapping[str, str]
COMMANDS: tuple[str, ...]

class FTPConnection(Connection):
    parser: FTPParser | None
    base_path: str
    host: str
    mode: str
    follow_links: bool
    data_server: FTPDataServer | None
    remaining: str | None
    cwd: str
    username: str
    password: str

    def __init__(
        self,
        base_path: str = ...,
        host: str = ...,
        mode: str = ...,
        follow_links: bool = ...,
        *args,
        **kwargs
    ): ...
    def open(self, *args, **kwargs): ...
    def close(self, *args, **kwargs): ...
    def parse(self, data: bytes) -> int: ...
    def send_ftp(
        self,
        code: int,
        message: str = ...,
        lines: Sequence[str] = ...,
        simple: bool = ...,
        delay: bool = ...,
        callback: Callable[[Connection], Any] | None = ...,
    ) -> int: ...
    def send_ftp_base(
        self,
        code: int,
        message: str = ...,
        delay: bool = ...,
        callback: Callable[[Connection], Any] | None = ...,
    ) -> int: ...
    def send_ftp_lines(
        self,
        code: int,
        message: str = ...,
        lines: Sequence[str] = ...,
        simple: bool = ...,
        delay: bool = ...,
        callback: Callable[[Connection], Any] | None = ...,
    ) -> int: ...
    def ready(self): ...
    def ok(self): ...
    def not_ok(self): ...
    def flush_ftp(self): ...
    def data_ftp(self, data: bytes): ...
    def closed_ftp(self): ...
    def flush_list(self): ...
    def flush_retr(self): ...
    def flush_stor(self): ...
    def on_flush_list(self, connection: Connection): ...
    def on_flush_retr(self, connection: Connection): ...
    def on_line(self, code: str, message: str, is_final: bool = ...): ...
    def on_user(self, message: str): ...
    def on_syst(self, message: str): ...
    def on_feat(self, message: str): ...
    def on_opts(self, message: str): ...
    def on_pwd(self, message: str): ...
    def on_type(self, message: str): ...
    def on_pasv(self, message: str): ...
    def on_port(self, message: str): ...
    def on_dele(self, message: str): ...
    def on_mkd(self, message: str): ...
    def on_rmd(self, message: str): ...
    def on_rnfr(self, message: str): ...
    def on_rnto(self, message: str): ...
    def on_cdup(self, message: str): ...
    def on_cwd(self, message: str): ...
    def on_size(self, message: str): ...
    def on_mdtm(self, message: str): ...
    def on_noop(self, message: str): ...
    def on_quit(self, message: str): ...
    def on_list(self, message: str): ...
    def on_retr(self, message: str): ...
    def on_stor(self, message: str): ...
    def _file_send(self, connection: Connection): ...
    def _file_finish(self, connection: Connection): ...
    def _data_open(self) -> FTPDataServer: ...
    def _data_close(self): ...
    def _list(self) -> str: ...
    def _to_unix(self, mode: stat_result) -> str: ...
    def _get_path(self, extra: str | None = ...) -> str: ...

class FTPDataServer(StreamServer):
    connection: FTPConnection
    container: ContainerServer
    accepted: Connection | None

    def __init__(
        self, connection: FTPConnection, container: ContainerServer, *args, **kwargs
    ): ...
    def on_connection_c(self, connection: Connection): ...
    def on_connection_d(self, connection: Connection): ...
    def on_data(self, connection: Connection, data: bytes): ...
    def send_ftp(
        self,
        data: bytes | str,
        delay: bool = ...,
        force: bool = ...,
        callback: Callable[[Connection], Any] | None = ...,
    ) -> int: ...
    def flush_ftp(self): ...
    def close_ftp(self): ...

class FTPServer(ContainerServer):
    base_path: str
    auth_s: str
    follow_links: bool

    def __init__(
        self,
        base_path: str = ...,
        auth_s: str = ...,
        follow_links: bool = ...,
        *args,
        **kwargs
    ): ...
    def serve(  # type: ignore[override]
        self, host: str = ..., port: int = ..., *args, **kwargs
    ): ...
    def on_connection_c(self, connection: Connection): ...
    def on_data(self, connection: Connection, data: bytes): ...
    def on_serve(self): ...
    def build_connection(  # type: ignore[override]
        self, socket: socket, address: tuple[str, int] | str | None, ssl: bool = ...
    ) -> Connection: ...
    def on_line_ftp(self, connection: FTPConnection, code: str, message: str): ...
