from socket import socket
from typing import Any, BinaryIO, Callable, Sequence

from netius import Connection, StreamServer
from netius.common import POPParser

INITIAL_STATE: int
HELO_STATE: int
AUTH_STATE: int
SESSION_STATE: int
CHUNK_SIZE: int
CAPABILITIES: tuple[str, ...]
AUTH_METHODS: tuple[str, ...]

class POPConnection(Connection):
    parser: POPParser | None
    host: str
    username: str | None
    token_buf: list[bytes]
    count: int
    byte_c: int
    size: int
    file: BinaryIO | None
    sizes: Sequence[int]
    keys: Sequence[str]
    state: int

    def __init__(self, host: str = ..., *args, **kwargs): ...
    def open(self, *args, **kwargs): ...
    def close(self, *args, **kwargs): ...
    def parse(self, data: bytes) -> int | None: ...
    def send_pop(
        self,
        message: str = ...,
        lines: Sequence[str] = ...,
        status: str = ...,
        delay: bool = ...,
        callback: Callable[[Connection], Any] | None = ...,
    ) -> int: ...
    def ready(self): ...
    def starttls(self): ...
    def capa(self): ...
    def auth(self): ...
    def accept(self): ...
    def stat(self): ...
    def list(self): ...
    def uidl(self): ...
    def retr(self, index: int): ...
    def dele(self, index: int): ...
    def bye(self): ...
    def ok(self): ...
    def not_implemented(self): ...
    def on_line(self, code: str, message: str): ...
    def on_stls(self, message: str): ...
    def on_capa(self, message: str): ...
    def on_auth(self, message: str): ...
    def on_stat(self, message: str): ...
    def on_list(self, message: str): ...
    def on_uidl(self, message: str): ...
    def on_retr(self, message: str): ...
    def on_dele(self, message: str): ...
    def on_quit(self, message: str): ...
    def on_user(self, token: bytes): ...
    def assert_s(self, expected: int): ...

class POPServer(StreamServer):
    adapter_s: str
    auth_s: str

    def __init__(self, adapter_s: str = ..., auth_s: str = ..., *args, **kwargs): ...
    def serve(  # type: ignore[override]
        self, host: str = ..., port: int = ..., *args, **kwargs
    ): ...
    def on_connection_c(self, connection: Connection): ...
    def on_connection_d(self, connection: Connection): ...
    def on_data(self, connection: Connection, data: bytes): ...
    def on_serve(self): ...
    def build_connection(  # type: ignore[override]
        self, socket: socket, address: tuple[str, int] | str | None, ssl: bool = ...
    ) -> Connection: ...
    def on_line_pop(self, connection: POPConnection, code: str, message: str): ...
    def on_auth_pop(self, connection: POPConnection, username: str, password: str): ...
    def on_stat_pop(self, connection: POPConnection): ...
    def on_list_pop(self, connection: POPConnection): ...
    def on_uidl_pop(self, connection: POPConnection): ...
    def on_retr_pop(self, connection: POPConnection, index: int): ...
    def on_dele_pop(self, connection: POPConnection, index: int): ...
