from socket import socket
from typing import Any, Callable, Sequence

from netius import Connection, StreamServer
from netius.common import SMTPParser

INITIAL_STATE: int
HELO_STATE: int
HEADER_STATE: int
DATA_STATE: int
USERNAME_STATE: int
PASSWORD_STATE: int
TERMINATION_SIZE: int
CAPABILITIES: tuple[str, ...]
COMMANDS: tuple[str, ...]

class SMTPConnection(Connection):
    parser: SMTPParser | None
    host: str
    chost: str | None
    identifier: str | None
    time: float
    keys: list[str]
    from_l: list[str]
    to_l: list[str]
    previous: bytes
    tail: bytes
    state: int

    def __init__(self, host: str = ..., *args, **kwargs): ...
    def open(self, *args, **kwargs): ...
    def close(self, *args, **kwargs): ...
    def parse(self, data: bytes) -> int | None: ...
    def send_smtp(
        self,
        code: int,
        message: str = ...,
        lines: Sequence[str] = ...,
        delay: bool = ...,
        callback: Callable[[Connection], Any] | None = ...,
    ) -> int: ...
    def send_smtp_base(
        self,
        code: int,
        message: str = ...,
        delay: bool = ...,
        callback: Callable[[Connection], Any] | None = ...,
    ) -> int: ...
    def send_smtp_lines(
        self,
        code: int,
        message: str = ...,
        lines: Sequence[str] = ...,
        delay: bool = ...,
        callback: Callable[[Connection], Any] | None = ...,
    ) -> int: ...
    def ready(self): ...
    def helo(self, host: str): ...
    def ehlo(self, host: str): ...
    def starttls(self): ...
    def auth(self, method: str, data: str): ...
    def auth_plain(self, data: str | bytes): ...
    def auth_login(self, data: str | bytes): ...
    def data(self): ...
    def queued(self, index: int = ...): ...
    def bye(self): ...
    def ok(self): ...
    def not_implemented(self): ...
    def on_username(self, data: bytes): ...
    def on_password(self, data: bytes): ...
    def on_raw_data(self, data: bytes): ...
    def unstuff(self, data: bytes) -> bytes: ...
    def on_line(self, code: str, message: str, is_final: bool = ...): ...
    def on_helo(self, message: str): ...
    def on_ehlo(self, message: str): ...
    def on_starttls(self, message: str): ...
    def on_auth(self, message: str): ...
    def on_mail(self, message: str): ...
    def on_rcpt(self, message: str): ...
    def on_data(self, message: str): ...
    def on_quit(self, message: str): ...
    def assert_s(self, expected: int): ...
    def to_s(self) -> str: ...
    def received_s(self, for_s: bool = ...) -> str: ...
    def reset_message(self): ...

class SMTPServer(StreamServer):
    host_g: str | None
    adapter_s: str
    auth_s: str
    locals: Sequence[str]

    def __init__(
        self,
        adapter_s: str = ...,
        auth_s: str = ...,
        locals: Sequence[str] = ...,
        *args,
        **kwargs
    ): ...
    def serve(  # type: ignore[override]
        self, host: str = ..., port: int = ..., *args, **kwargs
    ): ...
    def on_connection_c(self, connection: Connection): ...
    def on_data(self, connection: Connection, data: bytes): ...
    def on_serve(self): ...
    def build_connection(  # type: ignore[override]
        self, socket: socket, address: tuple[str, int] | str | None, ssl: bool = ...
    ) -> Connection: ...
    def on_line_smtp(self, connection: SMTPConnection, code: str, message: str): ...
    def on_auth_smtp(
        self, connection: SMTPConnection, username: str, password: str
    ): ...
    def on_header_smtp(
        self,
        connection: SMTPConnection,
        from_l: Sequence[str],
        to_l: Sequence[str],
    ): ...
    def on_data_smtp(self, connection: SMTPConnection, data: bytes): ...
    def on_message_smtp(self, connection: SMTPConnection): ...
    def _locals(self, sequence: Sequence[str], prefix: str = ...) -> list[str]: ...
    def _remotes(self, sequence: Sequence[str], prefix: str = ...) -> list[str]: ...
    def _emails(self, sequence: Sequence[str], prefix: str = ...) -> list[str]: ...
    def _users(self, emails: Sequence[str]) -> list[str]: ...
    def _is_local(self, email: str) -> bool: ...
