from socket import socket as Socket
from typing import Any, Mapping

from netius import Connection, Protocol, ServerAgent, Transport
from netius.clients import RawClient, RawProtocol
from netius.common import SOCKSParser

GRANTED: int
REJECTED: int
FAILED_CLIENT: int
FAILED_AUTH: int
GRANTED_EXTRA: int
BUFFER_RATIO: float
MIN_RATIO: float
MAX_PENDING: int

class SOCKSConnection(Connection):
    parser: SOCKSParser | None

    def __init__(self, *args, **kwargs): ...
    def open(self, *args, **kwargs): ...
    def close(self, *args, **kwargs): ...
    def send_response(self, status: int = ...) -> int: ...
    def send_response_extra(self, status: int = ...) -> int: ...
    def send_auth(self, version: int | None = ..., method: int = ...) -> int: ...
    def get_version(self) -> int: ...
    def parse(self, data: bytes) -> int: ...
    def on_data(self): ...
    def on_auth(self): ...

class SOCKSServer(ServerAgent):
    rules: Mapping[str, Any]
    throttle: bool
    max_pending: int
    min_pending: int
    conn_map: dict[RawProtocol, SOCKSConnection]
    raw_protocol: RawProtocol

    def __init__(
        self,
        rules: Mapping[str, Any] = ...,
        throttle: bool = ...,
        max_pending: int = ...,
        *args,
        **kwargs
    ): ...
    def cleanup(self): ...
    def on_data(self, connection: SOCKSConnection, data: bytes): ...
    def on_data_socks(self, connection: SOCKSConnection, parser: SOCKSParser): ...
    def on_auth_socks(self, connection: SOCKSConnection, parser: SOCKSParser): ...
    def on_connection_d(self, connection: SOCKSConnection): ...
    def build_connection(
        self, socket: Socket, address: tuple[str, int] | str | None, ssl: bool = ...
    ) -> SOCKSConnection: ...
    def _throttle(self, _connection: Transport | Protocol): ...
    def _raw_throttle(self, connection: SOCKSConnection): ...
    def _on_raw_connect(self, client: RawClient, _connection: RawProtocol): ...
    def _on_raw_data(
        self, client: RawClient, _connection: RawProtocol, data: bytes
    ): ...
    def _on_raw_close(self, client: RawClient, _connection: RawProtocol): ...
