from typing import IO, Any, Callable, Mapping

from netius import DatagramServer

class TFTPSession:
    owner: TFTPServer
    name: str | None
    mode: str | None
    file: IO[bytes] | None
    completed: bool
    sequence: int

    def __init__(
        self, owner: TFTPServer, name: str | None = ..., mode: str | None = ...
    ): ...
    def close(self): ...
    def reset(self): ...
    def next(self, size: int = ..., increment: bool = ...) -> bytes | None: ...
    def ack(self, size: int = ..., increment: bool = ...) -> bytes | None: ...
    def increment(self): ...
    def get_info(self) -> str: ...
    def print_info(self): ...
    def _get_file(self, allow_absolute: bool = ...) -> IO[bytes]: ...

class TFTPRequest:
    parsers_m: tuple[Callable[[TFTPRequest], Any], ...] | None
    parsers_l: int | None
    data: bytes
    session: TFTPSession

    def __init__(self, data: bytes, session: TFTPSession): ...
    @classmethod
    def generate(cls): ...
    def get_info(self) -> str: ...
    def print_info(self): ...
    def parse(self): ...
    def get_type(self) -> int: ...
    def get_type_s(self) -> str | None: ...
    def response(self, options: Mapping[Any, Any] = ...) -> bytes | None: ...
    @classmethod
    def _parse_rrq(cls, self: TFTPRequest): ...
    @classmethod
    def _parse_wrq(cls, self: TFTPRequest): ...
    @classmethod
    def _parse_data(cls, self: TFTPRequest): ...
    @classmethod
    def _parse_ack(cls, self: TFTPRequest): ...
    @classmethod
    def _parse_error(cls, self: TFTPRequest): ...
    @classmethod
    def _str(cls, data: bytes) -> tuple[str, bytes]: ...

class TFTPServer(DatagramServer):
    ALLOWED_OPERATIONS: tuple[int, ...]
    base_path: str
    sessions: dict[Any, TFTPSession]

    def __init__(self, base_path: str = ..., *args, **kwargs): ...
    def serve(self, port: int = ..., *args, **kwargs): ...  # type: ignore[override]
    def on_data(self, address: Any, data: bytes): ...
    def on_serve(self): ...
    def on_data_tftp(self, address: Any, request: TFTPRequest): ...
    def on_error_tftp(self, address: Any, exception: Exception): ...
