from typing import Any, Mapping, Sequence

from netius import ContainerServer, Observable
from netius.clients import (
    DHTClient,
    DHTResponse,
    HTTPClient,
    HTTPProtocol,
    TorrentClient,
    TorrentConnection,
)
from netius.common import FileStream, FilesStream, HTTPParser

REFRESH_TIME: float
PRINT_TIME: float
ID_STRING: str
BLOCK_SIZE: int
THRESHOLD_END: int
MAX_MISSING: int
MAX_PEERS: int
PEER_PATHS: tuple[str, ...]

class Pieces(Observable):
    length: int
    piece_length: int
    number_pieces: int
    number_blocks: int
    final_blocks: int
    bitfield: list[bool]
    mask: list[bool]

    def __init__(self, length: int, number_pieces: int, number_blocks: int): ...
    def piece(self, index: int) -> bool: ...
    def piece_blocks(self, index: int) -> int: ...
    def piece_size(self, index: int) -> int: ...
    def block(self, index: int, begin: int) -> bool: ...
    def block_size(self, index: int, begin: int) -> int: ...
    def pop_block(
        self, bitfield: Sequence[bool] | bytes, mark: bool = ...
    ) -> tuple[int, int, int] | None: ...
    def push_block(self, index: int, begin: int): ...
    def mark_piece(self, index: int, value: bool = ...): ...
    def mark_block(self, index: int, begin: int, value: bool = ...): ...
    def update_block(self, index: int, mark: bool = ...) -> int: ...
    def update_piece(self, index: int): ...
    @property
    def total_pieces(self) -> int: ...
    @property
    def marked_pieces(self) -> int: ...
    @property
    def missing_pieces(self, max_missing: int = ...) -> list[int]: ...
    @property
    def total_blocks(self) -> int: ...
    @property
    def marked_blocks(self) -> int: ...
    @property
    def missing_blocks(self, max_missing: int = ...) -> list[int]: ...
    def _and(
        self, first: Sequence[bool] | bytes, second: Sequence[bool]
    ) -> list[bool]: ...

class TorrentTask(Observable):
    owner: TorrentServer | None
    target_path: str
    torrent_path: str | None
    info_hash: bytes | None
    start: float
    uploaded: int
    downloaded: int
    unchoked: int
    next_refresh: float
    info: dict[str, Any]
    file: FileStream | FilesStream | None
    requested: Pieces | None
    stored: Pieces | None
    connections: list[TorrentConnection]
    peers: list[dict[str, Any]]
    peers_m: dict[tuple[str, int], dict[str, Any]]

    def __init__(
        self,
        owner: TorrentServer,
        target_path: str,
        torrent_path: str | None = ...,
        info_hash: bytes | None = ...,
    ): ...
    def load(self): ...
    def unload(self): ...
    def on_close(self, connection: TorrentConnection): ...
    def ticks(self): ...
    def refresh(self): ...
    def on_choked(self, connection: TorrentConnection): ...
    def on_unchoked(self, connection: TorrentConnection): ...
    def on_block(self, pieces: Pieces, index: int, begin: int): ...
    def on_piece(self, pieces: Pieces, index: int): ...
    def on_complete(self, pieces: Pieces): ...
    def on_dht(self, response: DHTResponse | None): ...
    def on_tracker(
        self, client: HTTPProtocol, parser: HTTPParser, result: Mapping[str, Any]
    ): ...
    def has_metadata(self) -> bool: ...
    def set_metadata(self, metadata: bytes): ...
    def load_info(self, torrent_path: str) -> dict[str, Any]: ...
    def load_file(self): ...
    def load_single(self): ...
    def load_multiple(self): ...
    def unload_file(self): ...
    def load_pieces(self): ...
    def unload_pieces(self): ...
    def pieces_tracker(self): ...
    def set_data(self, data: bytes, index: int, begin: int): ...
    def write_data(self, data: bytes, offset: int): ...
    def set_dht(self, peer_t: tuple[str, int], port: int): ...
    def peers_dht(self): ...
    def peers_tracker(self): ...
    def peers_file(self): ...
    def connect_peers(self): ...
    def disconnect_peers(self): ...
    def connect_peer(self, peer: dict[str, Any]): ...
    def info_string(self) -> str: ...
    def left(self) -> int: ...
    def speed(self) -> float: ...
    def speed_s(self) -> str: ...
    def eta(self) -> float: ...
    def eta_s(self) -> str: ...
    def percent(self) -> float: ...
    def pop_block(
        self, bitfield: Sequence[bool] | bytes
    ) -> tuple[int, int, int] | None: ...
    def push_block(self, index: int, begin: int): ...
    def verify_piece(self, index: int): ...
    def confirm_piece(self, index: int): ...
    def refute_piece(self, index: int): ...
    def extend_peers(self, peers: Sequence[dict[str, Any]]): ...
    def add_peer(self, peer: dict[str, Any]): ...
    def remove_peer(self, peer: dict[str, Any]): ...
    def _is_single(self) -> bool: ...
    def _verify_piece(self, index: int, file: FileStream | FilesStream): ...

class TorrentServer(ContainerServer):
    peer_id: str
    max_peers: int
    client: TorrentClient
    http_client: HTTPClient
    dht_client: DHTClient
    tasks: list[TorrentTask]

    def __init__(self, max_peers: int = ..., *args, **kwargs): ...
    def on_serve(self): ...
    def cleanup(self): ...
    def ticks(self): ...
    def download(
        self,
        target_path: str,
        torrent_path: str | None = ...,
        info_hash: bytes | None = ...,
        close: bool = ...,
    ) -> TorrentTask: ...
    def add_task(self, task: TorrentTask): ...
    def remove_task(self, task: TorrentTask): ...
    def cleanup_tasks(self): ...
    def _generate_id(self) -> str: ...
