from socket import socket as Socket

from netius import Connection, StreamServer

class WSConnection(Connection):
    handshake: bool
    method: str | None
    path: str | None
    version: str | None
    buffer_l: list[bytes]
    headers: dict[str, str]

    def __init__(self, *args, **kwargs): ...
    def send_ws(self, data: bytes | str) -> int: ...
    def recv_ws(self, size: int = ...) -> tuple[bytes, bytes]: ...
    def add_buffer(self, data: bytes): ...
    def get_buffer(self, delete: bool = ...) -> bytes: ...
    def do_handshake(self): ...
    def accept_key(self) -> str: ...

class WSServer(StreamServer):
    MAGIC_VALUE: str

    def on_data(self, connection: Connection, data: bytes): ...
    def build_connection(  # type: ignore[override]
        self, socket: Socket, address: tuple[str, int] | str | None, ssl: bool = ...
    ) -> WSConnection: ...
    def send_ws(self, connection: Connection, data: bytes | str) -> int: ...
    def on_data_ws(self, connection: Connection, data: bytes): ...
    def on_handshake(self, connection: Connection): ...
    def _handshake_response(self, accept_key: str) -> str: ...
