from ctypes import CDLL
from socket import socket as Socket
from threading import Condition, RLock, Thread as BaseThread
from typing import IO, Any, Callable

CALLABLE_WORK: int

class Thread(BaseThread):
    identifier: int
    owner: ThreadPool | None

    def __init__(
        self, identifier: int, owner: ThreadPool | None = ..., *args, **kwargs
    ): ...
    @classmethod
    def available(cls) -> bool: ...
    def stop(self): ...
    def run(self): ...
    def tick(self): ...
    def execute(self, work: tuple[Any, ...]): ...

class ThreadPool:
    base: type[Thread]
    count: int
    instances: list[Thread]
    queue: list[tuple[Any, ...]]
    condition: Condition

    def __init__(self, base: type[Thread] = ..., count: int = ...): ...
    def start(self): ...
    def stop(self, join: bool = ...): ...
    def build(self): ...
    def peek(self) -> tuple[Any, ...] | None: ...
    def pop(self, lock: bool = ...) -> tuple[Any, ...]: ...
    def push(self, work: tuple[Any, ...], lock: bool = ...): ...
    def push_callable(self, callable: Callable[[], Any]): ...

class EventPool(ThreadPool):
    events: list[tuple[Any, ...]]
    event_lock: RLock

    def __init__(self, base: type[Thread] = ..., count: int = ...): ...
    def stop(self, join: bool = ...): ...
    def push_event(self, event: tuple[Any, ...]): ...
    def pop_event(self) -> tuple[Any, ...]: ...
    def pop_all(self, denotify: bool = ...) -> list[tuple[Any, ...]]: ...
    def notify(self): ...
    def denotify(self): ...
    def eventfd(self) -> EventFile: ...

class EventFile:
    closed: bool

    def __init__(self, *args, **kwargs): ...
    def close(self): ...
    def fileno(self) -> int | None: ...
    def rfileno(self) -> int | None: ...
    def wfileno(self) -> int | None: ...
    def notify(self): ...
    def denotify(self): ...

class UnixEventFile(EventFile):
    _LIBC: CDLL | None

    def __init__(self, *args, **kwargs): ...
    @classmethod
    def available(cls) -> bool: ...
    @classmethod
    def libc(cls) -> CDLL | None: ...
    def close(self): ...
    def notify(self): ...
    def denotify(self): ...
    def _read(self, length: int = ...) -> bytes | None: ...
    def _write(self, value: int): ...

class PipeEventFile(EventFile):
    def __init__(self, *args, **kwargs): ...
    @classmethod
    def available(cls) -> bool: ...
    def close(self): ...
    def notify(self): ...
    def denotify(self): ...
    def _read(self, length: int = ...) -> bytes | None: ...
    def _write(self, data: bytes): ...

class SocketEventFile(EventFile):
    def __init__(self, *args, **kwargs): ...
    def close(self): ...
    def notify(self): ...
    def denotify(self): ...
    def _read(self, length: int = ...) -> bytes | None: ...
    def _write(self, data: bytes): ...
