import netius as netius
import netius.common.util as util

__version__: str
__revision__: str
__date__: str
def prime(number_bits): ...
def is_prime(number): ...
def relatively_prime(first, second): ...
def gcd(first, second): ...
def egcd(first, second): ...
def modinv(first, second): ...
def random_integer_interval(min_value, max_value): ...
def random_primality(number, k): ...
def jacobi_witness(x, n): ...
def jacobi(a, b): ...
def ceil_integer(value): ...
