"""
This type stub file was generated by pyright.
"""

__author__ = ...
__version__ = ...
__revision__ = ...
__date__ = ...
__copyright__ = ...
__license__ = ...
def dkim_sign(message, selector, domain, private_key, identity=..., separator=..., creation=...):
    ...

def dkim_headers(headers):
    ...

def dkim_body(body): # -> bytes:
    ...

def dkim_fold(header, length=...):
    """
    Folds a header line into multiple line feed separated lines
    at column length defined (defaults to 72).

    This is required so that the header field is defined according
    to the dkim rules and the default mime encoding.

    :type header: String
    :param header: The string value of the header that is going to
    be folded into multiple lines.
    :type length: int
    :param length: The maximum length of a column until it gets
    broken into multiple lines (in case it's possible).
    :rtype: String
    :return: The folded string value for the header after the correct
    processing of the string value.
    """
    ...

def dkim_generate(domain, suffix=..., number_bits=...): # -> dict[str, bytes | str | Any]:
    ...

