import netius as netius
import netius.common.asn as asn
import netius.common.mime as mime
import netius.common.rsa as rsa
import netius.common.util as util
from _typeshed import Incomplete

__version__: str
__revision__: str
__date__: str
def dkim_sign(message, selector, domain, private_key, identity: Incomplete | None = ..., separator: str = ..., creation: Incomplete | None = ...): ...
def dkim_headers(headers): ...
def dkim_body(body): ...
def dkim_fold(header, length: int = ...): ...
def dkim_generate(domain, suffix: Incomplete | None = ..., number_bits: int = ...): ...
