"""
This type stub file was generated by pyright.
"""

from . import parser

__author__ = ...
__version__ = ...
__revision__ = ...
__date__ = ...
__copyright__ = ...
__license__ = ...
SEPARATOR_REGEX = ...
class FTPParser(parser.Parser):
    def __init__(self, owner, store=...) -> None:
        ...
    
    def parse(self, data): # -> int:
        """
        Parses the provided data chunk, changing the current
        state of the parser accordingly and returning the
        number of processed bytes from it.

        :type data: String
        :param data: The string containing the data to be parsed
        in the current parse operation.
        :rtype: int
        :return: The amount of bytes of the data string that have
        been "parsed" in the current parse operation.
        """
        ...
    


