import netius as netius
from typing import ClassVar

__version__: str
__revision__: str
__date__: str

class GeoResolver:
    DB_NAME: ClassVar[str] = ...
    DOWNLOAD_URL: ClassVar[str] = ...
    VALID: ClassVar[tuple] = ...
    PREFIXES: ClassVar[tuple] = ...
    _db: ClassVar[None] = ...
    @classmethod
    def resolve(cls, address, simplified: bool = ...): ...
    @classmethod
    def _simplify(cls, result, locale: str = ..., valid: tuple = ...): ...
    @classmethod
    def _get_db(cls): ...
    @classmethod
    def _try_all(cls, prefixes: tuple = ...): ...
    @classmethod
    def _try_db(cls, path: str = ..., download: bool = ...): ...
    @classmethod
    def _download_db(cls, path: str = ...): ...
    @classmethod
    def _store_db(cls, contents, path: str = ...): ...
