import netius as netius
import netius.base.observer
from typing import ClassVar

__version__: str
__revision__: str
__date__: str

class Parser(netius.base.observer.Observable):
    FIELDS: ClassVar[tuple] = ...
    def __init__(self, owner) -> None: ...
    @classmethod
    def mock(cls, owner, state): ...
    def build(self): ...
    def destroy(self): ...
    def get_state(self): ...
    def set_state(self, state): ...
    def info_dict(self): ...
    def parse(self, data): ...
