__version__: str
__revision__: str
__date__: str

class PriorityDict(dict):
    def __init__(self, *args, **kwargs) -> None: ...
    def __setitem__(self, key, val) -> None: ...
    def smallest(self): ...
    def pop_smallest(self): ...
    def setdefault(self, key, val): ...
    def update(self, *args, **kwargs): ...
    def sorted_iter(self): ...
    def _rebuild_heap(self): ...
def file_iterator(file_object, chunk_size: int = ...): ...
