import netius as netius

__version__: str
__revision__: str
__date__: str

class TLSContextDict(dict):
    def __init__(self, owner, domains, *args, **kwargs) -> None: ...
    def load(self, domains): ...
    def has_definition(self, domain): ...
    def cer_path(self, domain): ...
    def key_path(self, domain): ...

class LetsEncryptDict(TLSContextDict):
    def __init__(self, owner, domains, *args, **kwargs) -> None: ...
    def cer_path(self, domain): ...
    def key_path(self, domain): ...
