import netius as netius
import netius.common.parser
import netius.common.parser as parser

__version__: str
__revision__: str
__date__: str
HANDSHAKE_SIZE: int
TORRENT_TYPES: dict
def info_hash(root): ...
def bencode(root): ...
def bdecode(data): ...
def chunk(item): ...
def dechunk(chunks): ...

class TorrentParser(netius.common.parser.Parser):
    def __init__(self, owner, store: bool = ...) -> None: ...
    def build(self): ...
    def destroy(self): ...
    def parse(self, data): ...
    def _join(self, data): ...
    def _parse_handshake(self, data): ...
    def _parse_message(self, data): ...
