import netius as netius

__version__: str
__revision__: str
__date__: str
def encode_ws(data, final: bool = ..., opcode: int = ..., mask: bool = ...): ...
def decode_ws(data): ...
def assert_ws(data_l, size): ...
