from netius import Connection
from netius.base.common import AbstractBase
from netius.middleware import Middleware

class DummyMiddleware(Middleware):
    def start(self): ...
    def stop(self): ...
    def on_connection_c(self, owner: AbstractBase, connection: Connection): ...
