name: Deploy Workflow
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Build
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.14]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v7
      - name: Print Python version
        run: python --version
      - name: Install runtime dependencies
        run: |
          pip install -r requirements.txt
          pip install -r extra.txt
      - name: Check code formatting with black
        run: |
          pip install black
          black . --check
        if: matrix.python-version == '3.14'
      - name: Run unit tests
        run: |
          pip install pytest
          HTTPBIN=httpbin.bemisc.com pytest
      - name: Build and publish package to PyPI
        run: |
          pip install twine build
          python -m build
          python -m twine upload -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} dist/*
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
